// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import org.adorsys.adpharma.domain.AdPharmaBaseEntity;
import org.adorsys.adpharma.domain.FootPrint;

privileged aspect AdPharmaBaseEntity_Roo_JavaBean {
    
    public Long AdPharmaBaseEntity.getId() {
        return this.id;
    }
    
    public void AdPharmaBaseEntity.setId(Long id) {
        this.id = id;
    }
    
    public FootPrint AdPharmaBaseEntity.getFootPrint() {
        return this.footPrint;
    }
    
    public void AdPharmaBaseEntity.setFootPrint(FootPrint footPrint) {
        this.footPrint = footPrint;
    }
    
}
