// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Date;
import java.util.Set;
import org.adorsys.adpharma.domain.Approvisionement;
import org.adorsys.adpharma.domain.Devise;
import org.adorsys.adpharma.domain.Etat;
import org.adorsys.adpharma.domain.Fournisseur;
import org.adorsys.adpharma.domain.LigneApprovisionement;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.Site;

privileged aspect Approvisionement_Roo_JavaBean {
    
    public String Approvisionement.getApprovisionementNumber() {
        return this.approvisionementNumber;
    }
    
    public void Approvisionement.setApprovisionementNumber(String approvisionementNumber) {
        this.approvisionementNumber = approvisionementNumber;
    }
    
    public String Approvisionement.getBordereauNumber() {
        return this.bordereauNumber;
    }
    
    public void Approvisionement.setBordereauNumber(String bordereauNumber) {
        this.bordereauNumber = bordereauNumber;
    }
    
    public Calendar Approvisionement.getDateBordereau() {
        return this.dateBordereau;
    }
    
    public void Approvisionement.setDateBordereau(Calendar dateBordereau) {
        this.dateBordereau = dateBordereau;
    }
    
    public PharmaUser Approvisionement.getAgentCreateur() {
        return this.agentCreateur;
    }
    
    public void Approvisionement.setAgentCreateur(PharmaUser agentCreateur) {
        this.agentCreateur = agentCreateur;
    }
    
    public Site Approvisionement.getMagasin() {
        return this.magasin;
    }
    
    public void Approvisionement.setMagasin(Site magasin) {
        this.magasin = magasin;
    }
    
    public Devise Approvisionement.getDevise() {
        return this.devise;
    }
    
    public void Approvisionement.setDevise(Devise devise) {
        this.devise = devise;
    }
    
    public Date Approvisionement.getDateCommande() {
        return this.dateCommande;
    }
    
    public void Approvisionement.setDateCommande(Date dateCommande) {
        this.dateCommande = dateCommande;
    }
    
    public Date Approvisionement.getDateLivraison() {
        return this.dateLivraison;
    }
    
    public void Approvisionement.setDateLivraison(Date dateLivraison) {
        this.dateLivraison = dateLivraison;
    }
    
    public Fournisseur Approvisionement.getFounisseur() {
        return this.founisseur;
    }
    
    public void Approvisionement.setFounisseur(Fournisseur founisseur) {
        this.founisseur = founisseur;
    }
    
    public Date Approvisionement.getDateReglement() {
        return this.dateReglement;
    }
    
    public void Approvisionement.setDateReglement(Date dateReglement) {
        this.dateReglement = dateReglement;
    }
    
    public BigDecimal Approvisionement.getMontantHt() {
        return this.montantHt;
    }
    
    public void Approvisionement.setMontantHt(BigDecimal montantHt) {
        this.montantHt = montantHt;
    }
    
    public BigDecimal Approvisionement.getMontantTtc() {
        return this.montantTtc;
    }
    
    public void Approvisionement.setMontantTtc(BigDecimal montantTtc) {
        this.montantTtc = montantTtc;
    }
    
    public BigDecimal Approvisionement.getMontantRemise() {
        return this.montantRemise;
    }
    
    public void Approvisionement.setMontantRemise(BigDecimal montantRemise) {
        this.montantRemise = montantRemise;
    }
    
    public BigDecimal Approvisionement.getMontantNap() {
        return this.montantNap;
    }
    
    public void Approvisionement.setMontantNap(BigDecimal montantNap) {
        this.montantNap = montantNap;
    }
    
    public Date Approvisionement.getDateCreation() {
        return this.dateCreation;
    }
    
    public void Approvisionement.setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    
    public Boolean Approvisionement.getUrgence() {
        return this.urgence;
    }
    
    public void Approvisionement.setUrgence(Boolean urgence) {
        this.urgence = urgence;
    }
    
    public Boolean Approvisionement.getCloturer() {
        return this.cloturer;
    }
    
    public void Approvisionement.setCloturer(Boolean cloturer) {
        this.cloturer = cloturer;
    }
    
    public Set<LigneApprovisionement> Approvisionement.getLigneApprivisionement() {
        return this.ligneApprivisionement;
    }
    
    public void Approvisionement.setLigneApprivisionement(Set<LigneApprovisionement> ligneApprivisionement) {
        this.ligneApprivisionement = ligneApprivisionement;
    }
    
    public Etat Approvisionement.getEtat() {
        return this.etat;
    }
    
    public void Approvisionement.setEtat(Etat etat) {
        this.etat = etat;
    }
    
    public String Approvisionement.getFiliale() {
        return this.filiale;
    }
    
    public void Approvisionement.setFiliale(String filiale) {
        this.filiale = filiale;
    }
    
}
