// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.AvoirClient;

privileged aspect AvoirClient_Roo_Entity {
    
    declare @type: AvoirClient: @Entity(name = "AvoirClient");
    
    declare @type: AvoirClient: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long AvoirClient.countAvoirClients() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AvoirClient o", Long.class).getSingleResult();
    }
    
    public static AvoirClient AvoirClient.findAvoirClient(Long id) {
        if (id == null) return null;
        return entityManager().find(AvoirClient.class, id);
    }
    
}
