// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.Caisse;

privileged aspect Caisse_Roo_Entity {
    
    declare @type: Caisse: @Entity(name = "Caisse");
    
    declare @type: Caisse: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long Caisse.countCaisses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Caisse o", Long.class).getSingleResult();
    }
    
    public static List<Caisse> Caisse.findAllCaisses() {
        return entityManager().createQuery("SELECT o FROM Caisse o", Caisse.class).getResultList();
    }
    
    public static Caisse Caisse.findCaisse(Long id) {
        if (id == null) return null;
        return entityManager().find(Caisse.class, id);
    }
    
}
