// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import org.adorsys.adpharma.domain.CategorieClient;

privileged aspect CategorieClient_Roo_Finder {
    
    public static TypedQuery<CategorieClient> CategorieClient.findCategorieClientsByCategorieNumberEquals(String categorieNumber) {
        if (categorieNumber == null || categorieNumber.length() == 0) throw new IllegalArgumentException("The categorieNumber argument is required");
        EntityManager em = CategorieClient.entityManager();
        TypedQuery<CategorieClient> q = em.createQuery("SELECT o FROM CategorieClient AS o WHERE o.categorieNumber = :categorieNumber", CategorieClient.class);
        q.setParameter("categorieNumber", categorieNumber);
        return q;
    }
    
}
