// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import org.adorsys.adpharma.domain.CategorieClient;
import org.adorsys.adpharma.domain.Client;
import org.adorsys.adpharma.domain.Genre;
import org.adorsys.adpharma.domain.TypeClient;

privileged aspect Client_Roo_JavaBean {
    
    public String Client.getClientNumber() {
        return this.clientNumber;
    }
    
    public void Client.setClientNumber(String clientNumber) {
        this.clientNumber = clientNumber;
    }
    
    public String Client.getNom() {
        return this.nom;
    }
    
    public void Client.setNom(String nom) {
        this.nom = nom;
    }
    
    public String Client.getPrenom() {
        return this.prenom;
    }
    
    public void Client.setPrenom(String prenom) {
        this.prenom = prenom;
    }
    
    public String Client.getNomComplet() {
        return this.nomComplet;
    }
    
    public void Client.setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }
    
    public String Client.getTelephoneFixe() {
        return this.telephoneFixe;
    }
    
    public void Client.setTelephoneFixe(String telephoneFixe) {
        this.telephoneFixe = telephoneFixe;
    }
    
    public String Client.getTelephoneMobile() {
        return this.telephoneMobile;
    }
    
    public void Client.setTelephoneMobile(String telephoneMobile) {
        this.telephoneMobile = telephoneMobile;
    }
    
    public String Client.getFax() {
        return this.fax;
    }
    
    public void Client.setFax(String fax) {
        this.fax = fax;
    }
    
    public String Client.getEmail() {
        return this.email;
    }
    
    public void Client.setEmail(String email) {
        this.email = email;
    }
    
    public Boolean Client.getCreditAutorise() {
        return this.creditAutorise;
    }
    
    public void Client.setCreditAutorise(Boolean creditAutorise) {
        this.creditAutorise = creditAutorise;
    }
    
    public Boolean Client.getRemiseAutorise() {
        return this.remiseAutorise;
    }
    
    public void Client.setRemiseAutorise(Boolean remiseAutorise) {
        this.remiseAutorise = remiseAutorise;
    }
    
    public BigDecimal Client.getPlafondCredit() {
        return this.plafondCredit;
    }
    
    public void Client.setPlafondCredit(BigDecimal plafondCredit) {
        this.plafondCredit = plafondCredit;
    }
    
    public String Client.getEmployeur() {
        return this.employeur;
    }
    
    public void Client.setEmployeur(String employeur) {
        this.employeur = employeur;
    }
    
    public Date Client.getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void Client.setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    
    public Genre Client.getSexe() {
        return this.sexe;
    }
    
    public void Client.setSexe(Genre sexe) {
        this.sexe = sexe;
    }
    
    public BigDecimal Client.getTauxCouverture() {
        return this.tauxCouverture;
    }
    
    public void Client.setTauxCouverture(BigDecimal tauxCouverture) {
        this.tauxCouverture = tauxCouverture;
    }
    
    public String Client.getNote() {
        return this.note;
    }
    
    public void Client.setNote(String note) {
        this.note = note;
    }
    
    public Client Client.getClientPayeur() {
        return this.clientPayeur;
    }
    
    public void Client.setClientPayeur(Client clientPayeur) {
        this.clientPayeur = clientPayeur;
    }
    
    public String Client.getClientPayeurNumber() {
        return this.clientPayeurNumber;
    }
    
    public void Client.setClientPayeurNumber(String clientPayeurNumber) {
        this.clientPayeurNumber = clientPayeurNumber;
    }
    
    public CategorieClient Client.getCategorie() {
        return this.categorie;
    }
    
    public void Client.setCategorie(CategorieClient categorie) {
        this.categorie = categorie;
    }
    
    public BigInteger Client.getTotalDette() {
        return this.totalDette;
    }
    
    public void Client.setTotalDette(BigInteger totalDette) {
        this.totalDette = totalDette;
    }
    
    public TypeClient Client.getTypeClient() {
        return this.typeClient;
    }
    
    public void Client.setTypeClient(TypeClient typeClient) {
        this.typeClient = typeClient;
    }
    
    public String Client.getMatricule() {
        return this.matricule;
    }
    
    public void Client.setMatricule(String matricule) {
        this.matricule = matricule;
    }
    
}
