// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.Client;

privileged aspect Client_Roo_Entity {
    
    declare @type: Client: @Entity(name = "Client");
    
    declare @type: Client: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long Client.countClients() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Client o", Long.class).getSingleResult();
    }
    
    public static List<Client> Client.findAllClients() {
        return entityManager().createQuery("SELECT o FROM Client o", Client.class).getResultList();
    }
    
    public static Client Client.findClient(Long id) {
        if (id == null) return null;
        return entityManager().find(Client.class, id);
    }
    
}
