// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import org.adorsys.adpharma.domain.Client;

privileged aspect Client_Roo_Finder {
    
    public static TypedQuery<Client> Client.findClientsByClientNumberEquals(String clientNumber) {
        if (clientNumber == null || clientNumber.length() == 0) throw new IllegalArgumentException("The clientNumber argument is required");
        EntityManager em = Client.entityManager();
        TypedQuery<Client> q = em.createQuery("SELECT o FROM Client AS o WHERE o.clientNumber = :clientNumber", Client.class);
        q.setParameter("clientNumber", clientNumber);
        return q;
    }
    
    public static TypedQuery<Client> Client.findClientsByNomCompletLike(String nomComplet) {
        if (nomComplet == null || nomComplet.length() == 0) throw new IllegalArgumentException("The nomComplet argument is required");
        nomComplet = nomComplet.replace('*', '%');
        if (nomComplet.charAt(0) != '%') {
            nomComplet = "%" + nomComplet;
        }
        if (nomComplet.charAt(nomComplet.length() - 1) != '%') {
            nomComplet = nomComplet + "%";
        }
        EntityManager em = Client.entityManager();
        TypedQuery<Client> q = em.createQuery("SELECT o FROM Client AS o WHERE LOWER(o.nomComplet) LIKE LOWER(:nomComplet)", Client.class);
        q.setParameter("nomComplet", nomComplet);
        return q;
    }
    
    public static TypedQuery<Client> Client.findClientsByNomEquals(String nom) {
        if (nom == null || nom.length() == 0) throw new IllegalArgumentException("The nom argument is required");
        EntityManager em = Client.entityManager();
        TypedQuery<Client> q = em.createQuery("SELECT o FROM Client AS o WHERE o.nom = :nom", Client.class);
        q.setParameter("nom", nom);
        return q;
    }
    
}
