// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import org.adorsys.adpharma.domain.CommandeFournisseur;
import org.adorsys.adpharma.domain.Etat;
import org.adorsys.adpharma.domain.Fournisseur;
import org.adorsys.adpharma.domain.LigneCmdFournisseur;
import org.adorsys.adpharma.domain.ModeSelection;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.Site;
import org.adorsys.adpharma.domain.TVA;

privileged aspect CommandeFournisseur_Roo_JavaBean {
    
    public String CommandeFournisseur.getCmdNumber() {
        return this.cmdNumber;
    }
    
    public void CommandeFournisseur.setCmdNumber(String cmdNumber) {
        this.cmdNumber = cmdNumber;
    }
    
    public Date CommandeFournisseur.getDateCreation() {
        return this.dateCreation;
    }
    
    public void CommandeFournisseur.setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    
    public Date CommandeFournisseur.getDateLimiteLivraison() {
        return this.dateLimiteLivraison;
    }
    
    public void CommandeFournisseur.setDateLimiteLivraison(Date dateLimiteLivraison) {
        this.dateLimiteLivraison = dateLimiteLivraison;
    }
    
    public Fournisseur CommandeFournisseur.getFournisseur() {
        return this.fournisseur;
    }
    
    public void CommandeFournisseur.setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }
    
    public Boolean CommandeFournisseur.getLivre() {
        return this.livre;
    }
    
    public void CommandeFournisseur.setLivre(Boolean livre) {
        this.livre = livre;
    }
    
    public Set<LigneCmdFournisseur> CommandeFournisseur.getLigneCommande() {
        return this.ligneCommande;
    }
    
    public void CommandeFournisseur.setLigneCommande(Set<LigneCmdFournisseur> ligneCommande) {
        this.ligneCommande = ligneCommande;
    }
    
    public ModeSelection CommandeFournisseur.getModeDeSelection() {
        return this.ModeDeSelection;
    }
    
    public void CommandeFournisseur.setModeDeSelection(ModeSelection ModeDeSelection) {
        this.ModeDeSelection = ModeDeSelection;
    }
    
    public Site CommandeFournisseur.getSite() {
        return this.site;
    }
    
    public void CommandeFournisseur.setSite(Site site) {
        this.site = site;
    }
    
    public PharmaUser CommandeFournisseur.getCreePar() {
        return this.creePar;
    }
    
    public void CommandeFournisseur.setCreePar(PharmaUser creePar) {
        this.creePar = creePar;
    }
    
    public Etat CommandeFournisseur.getEtatCmd() {
        return this.etatCmd;
    }
    
    public void CommandeFournisseur.setEtatCmd(Etat etatCmd) {
        this.etatCmd = etatCmd;
    }
    
    public Boolean CommandeFournisseur.getAnnuler() {
        return this.annuler;
    }
    
    public void CommandeFournisseur.setAnnuler(Boolean annuler) {
        this.annuler = annuler;
    }
    
    public BigDecimal CommandeFournisseur.getMontantHt() {
        return this.montantHt;
    }
    
    public void CommandeFournisseur.setMontantHt(BigDecimal montantHt) {
        this.montantHt = montantHt;
    }
    
    public BigDecimal CommandeFournisseur.getMontantTva() {
        return this.montantTva;
    }
    
    public void CommandeFournisseur.setMontantTva(BigDecimal montantTva) {
        this.montantTva = montantTva;
    }
    
    public BigDecimal CommandeFournisseur.getMontantTtc() {
        return this.montantTtc;
    }
    
    public void CommandeFournisseur.setMontantTtc(BigDecimal montantTtc) {
        this.montantTtc = montantTtc;
    }
    
    public TVA CommandeFournisseur.getTva() {
        return this.tva;
    }
    
    public void CommandeFournisseur.setTva(TVA tva) {
        this.tva = tva;
    }
    
}
