// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import org.adorsys.adpharma.domain.Client;
import org.adorsys.adpharma.domain.CommandeClient;
import org.adorsys.adpharma.domain.Etat;
import org.adorsys.adpharma.domain.LigneCmdClient;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.TypeCommande;

privileged aspect CommandeClient_Roo_JavaBean {
    
    public String CommandeClient.getCmdNumber() {
        return this.cmdNumber;
    }
    
    public void CommandeClient.setCmdNumber(String cmdNumber) {
        this.cmdNumber = cmdNumber;
    }
    
    public Date CommandeClient.getDateCreation() {
        return this.dateCreation;
    }
    
    public void CommandeClient.setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    
    public Client CommandeClient.getClient() {
        return this.client;
    }
    
    public void CommandeClient.setClient(Client client) {
        this.client = client;
    }
    
    public PharmaUser CommandeClient.getVendeur() {
        return this.vendeur;
    }
    
    public void CommandeClient.setVendeur(PharmaUser vendeur) {
        this.vendeur = vendeur;
    }
    
    public Etat CommandeClient.getStatus() {
        return this.status;
    }
    
    public void CommandeClient.setStatus(Etat status) {
        this.status = status;
    }
    
    public Boolean CommandeClient.getEncaisse() {
        return this.encaisse;
    }
    
    public void CommandeClient.setEncaisse(Boolean encaisse) {
        this.encaisse = encaisse;
    }
    
    public Boolean CommandeClient.getAnnuler() {
        return this.annuler;
    }
    
    public void CommandeClient.setAnnuler(Boolean annuler) {
        this.annuler = annuler;
    }
    
    public BigDecimal CommandeClient.getMontantHt() {
        return this.montantHt;
    }
    
    public void CommandeClient.setMontantHt(BigDecimal montantHt) {
        this.montantHt = montantHt;
    }
    
    public BigDecimal CommandeClient.getMontantTva() {
        return this.montantTva;
    }
    
    public void CommandeClient.setMontantTva(BigDecimal montantTva) {
        this.montantTva = montantTva;
    }
    
    public BigDecimal CommandeClient.getMontantTtc() {
        return this.montantTtc;
    }
    
    public void CommandeClient.setMontantTtc(BigDecimal montantTtc) {
        this.montantTtc = montantTtc;
    }
    
    public BigDecimal CommandeClient.getRemise() {
        return this.remise;
    }
    
    public void CommandeClient.setRemise(BigDecimal remise) {
        this.remise = remise;
    }
    
    public Long CommandeClient.getFactureId() {
        return this.factureId;
    }
    
    public void CommandeClient.setFactureId(Long factureId) {
        this.factureId = factureId;
    }
    
    public TypeCommande CommandeClient.getTypeCommande() {
        return this.typeCommande;
    }
    
    public void CommandeClient.setTypeCommande(TypeCommande typeCommande) {
        this.typeCommande = typeCommande;
    }
    
    public Set<LigneCmdClient> CommandeClient.getLineCommande() {
        return this.lineCommande;
    }
    
    public void CommandeClient.setLineCommande(Set<LigneCmdClient> lineCommande) {
        this.lineCommande = lineCommande;
    }
    
    public Client CommandeClient.getClientPaiyeur() {
        return this.clientPaiyeur;
    }
    
    public void CommandeClient.setClientPaiyeur(Client clientPaiyeur) {
        this.clientPaiyeur = clientPaiyeur;
    }
    
    public int CommandeClient.getTauxCouverture() {
        return this.tauxCouverture;
    }
    
    public void CommandeClient.setTauxCouverture(int tauxCouverture) {
        this.tauxCouverture = tauxCouverture;
    }
    
    public Boolean CommandeClient.getVentePartiel() {
        return this.ventePartiel;
    }
    
    public void CommandeClient.setVentePartiel(Boolean ventePartiel) {
        this.ventePartiel = ventePartiel;
    }
    
    public String CommandeClient.getAvoirNumber() {
        return this.avoirNumber;
    }
    
    public void CommandeClient.setAvoirNumber(String avoirNumber) {
        this.avoirNumber = avoirNumber;
    }
    
    public String CommandeClient.getNumeroBon() {
        return this.numeroBon;
    }
    
    public void CommandeClient.setNumeroBon(String numeroBon) {
        this.numeroBon = numeroBon;
    }
    
}
