// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.adorsys.adpharma.domain.CommandeClient;

privileged aspect CommandeClient_Roo_Json {
    
    public String CommandeClient.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static CommandeClient CommandeClient.fromJsonToCommandeClient(String json) {
        return new JSONDeserializer<CommandeClient>().use(null, CommandeClient.class).deserialize(json);
    }
    
    public static String CommandeClient.toJsonArray(Collection<CommandeClient> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<CommandeClient> CommandeClient.fromJsonArrayToCommandeClients(String json) {
        return new JSONDeserializer<List<CommandeClient>>().use(null, ArrayList.class).use("values", CommandeClient.class).deserialize(json);
    }
    
}
