// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import org.adorsys.adpharma.domain.EtatDette;

privileged aspect EtatDette_Roo_Entity {
    
    declare @type: EtatDette: @Entity;
    
    public static long EtatDette.countEtatDettes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM EtatDette o", Long.class).getSingleResult();
    }
    
    public static List<EtatDette> EtatDette.findAllEtatDettes() {
        return entityManager().createQuery("SELECT o FROM EtatDette o", EtatDette.class).getResultList();
    }
    
    public static EtatDette EtatDette.findEtatDette(Long id) {
        if (id == null) return null;
        return entityManager().find(EtatDette.class, id);
    }
    
    public static List<EtatDette> EtatDette.findEtatDetteEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM EtatDette o", EtatDette.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
