// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.EtatCredits;

privileged aspect EtatCredits_Roo_Entity {
    
    declare @type: EtatCredits: @Entity(name = "EtatCredits");
    
    declare @type: EtatCredits: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long EtatCredits.countEtatCreditses() {
        return entityManager().createQuery("SELECT COUNT(o) FROM EtatCredits o", Long.class).getSingleResult();
    }
    
    public static EtatCredits EtatCredits.findEtatCredits(Long id) {
        if (id == null) return null;
        return entityManager().find(EtatCredits.class, id);
    }
    
}
