// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.Facture;

privileged aspect Facture_Roo_Entity {
    
    declare @type: Facture: @Entity(name = "Facture");
    
    declare @type: Facture: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long Facture.countFactures() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Facture o", Long.class).getSingleResult();
    }
    
    public static List<Facture> Facture.findAllFactures() {
        return entityManager().createQuery("SELECT o FROM Facture o", Facture.class).getResultList();
    }
    
    public static Facture Facture.findFacture(Long id) {
        if (id == null) return null;
        return entityManager().find(Facture.class, id);
    }
    
}
