// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.adorsys.adpharma.domain.Facture;

privileged aspect Facture_Roo_Json {
    
    public String Facture.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Facture Facture.fromJsonToFacture(String json) {
        return new JSONDeserializer<Facture>().use(null, Facture.class).deserialize(json);
    }
    
    public static String Facture.toJsonArray(Collection<Facture> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Facture> Facture.fromJsonArrayToFactures(String json) {
        return new JSONDeserializer<List<Facture>>().use(null, ArrayList.class).use("values", Facture.class).deserialize(json);
    }
    
}
