// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.FamilleProduit;

privileged aspect FamilleProduit_Roo_Entity {
    
    declare @type: FamilleProduit: @Entity(name = "FamilleProduit");
    
    declare @type: FamilleProduit: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long FamilleProduit.countFamilleProduits() {
        return entityManager().createQuery("SELECT COUNT(o) FROM FamilleProduit o", Long.class).getSingleResult();
    }
    
    public static List<FamilleProduit> FamilleProduit.findAllFamilleProduits() {
        return entityManager().createQuery("SELECT o FROM FamilleProduit o", FamilleProduit.class).getResultList();
    }
    
    public static FamilleProduit FamilleProduit.findFamilleProduit(Long id) {
        if (id == null) return null;
        return entityManager().find(FamilleProduit.class, id);
    }
    
    public static List<FamilleProduit> FamilleProduit.findFamilleProduitEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM FamilleProduit o", FamilleProduit.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
