// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;

privileged aspect FamilleProduit_Roo_ToString {
    
    public String FamilleProduit.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Archived: ").append(getArchived()).append(", ");
        sb.append("FamilleNumber: ").append(getFamilleNumber()).append(", ");
        sb.append("FootPrint: ").append(getFootPrint()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("LibelleCourt: ").append(getLibelleCourt()).append(", ");
        sb.append("LibelleFamille: ").append(getLibelleFamille()).append(", ");
        sb.append("Note: ").append(getNote()).append(", ");
        sb.append("Version: ").append(getVersion());
        return sb.toString();
    }
    
}
