// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import org.adorsys.adpharma.domain.Filiale;

privileged aspect Filiale_Roo_JavaBean {
    
    public String Filiale.getFilialeNumber() {
        return this.filialeNumber;
    }
    
    public void Filiale.setFilialeNumber(String filialeNumber) {
        this.filialeNumber = filialeNumber;
    }
    
    public String Filiale.getLibelle() {
        return this.libelle;
    }
    
    public void Filiale.setLibelle(String libelle) {
        this.libelle = libelle;
    }
    
    public String Filiale.getDescription() {
        return this.description;
    }
    
    public void Filiale.setDescription(String description) {
        this.description = description;
    }
    
    public Boolean Filiale.getActif() {
        return this.actif;
    }
    
    public void Filiale.setActif(Boolean actif) {
        this.actif = actif;
    }
    
}
