// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import org.adorsys.adpharma.domain.FootPrint;

privileged aspect FootPrint_Roo_JavaBean {
    
    public String FootPrint.getBusinessKey() {
        return this.businessKey;
    }
    
    public void FootPrint.setBusinessKey(String businessKey) {
        this.businessKey = businessKey;
    }
    
    public String FootPrint.getBusinessName() {
        return this.businessName;
    }
    
    public void FootPrint.setBusinessName(String businessName) {
        this.businessName = businessName;
    }
    
    public Long FootPrint.getTechId() {
        return this.techId;
    }
    
    public void FootPrint.setTechId(Long techId) {
        this.techId = techId;
    }
    
}
