// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import org.adorsys.adpharma.domain.Etat;
import org.adorsys.adpharma.domain.Inventaire;
import org.adorsys.adpharma.domain.LigneInventaire;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.Site;

privileged aspect Inventaire_Roo_JavaBean {
    
    public String Inventaire.getNumeroInventaire() {
        return this.numeroInventaire;
    }
    
    public void Inventaire.setNumeroInventaire(String numeroInventaire) {
        this.numeroInventaire = numeroInventaire;
    }
    
    public PharmaUser Inventaire.getAgent() {
        return this.agent;
    }
    
    public void Inventaire.setAgent(PharmaUser agent) {
        this.agent = agent;
    }
    
    public BigDecimal Inventaire.getMontant() {
        return this.montant;
    }
    
    public void Inventaire.setMontant(BigDecimal montant) {
        this.montant = montant;
    }
    
    public Etat Inventaire.getEtat() {
        return this.etat;
    }
    
    public void Inventaire.setEtat(Etat etat) {
        this.etat = etat;
    }
    
    public String Inventaire.getNote() {
        return this.note;
    }
    
    public void Inventaire.setNote(String note) {
        this.note = note;
    }
    
    public Date Inventaire.getDateInventaire() {
        return this.dateInventaire;
    }
    
    public void Inventaire.setDateInventaire(Date dateInventaire) {
        this.dateInventaire = dateInventaire;
    }
    
    public Site Inventaire.getSite() {
        return this.site;
    }
    
    public void Inventaire.setSite(Site site) {
        this.site = site;
    }
    
    public Set<LigneInventaire> Inventaire.getLigneInventaire() {
        return this.ligneInventaire;
    }
    
    public void Inventaire.setLigneInventaire(Set<LigneInventaire> ligneInventaire) {
        this.ligneInventaire = ligneInventaire;
    }
    
}
