// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Version;
import org.adorsys.adpharma.domain.LicenceEntity;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LicenceEntity_Roo_Entity {
    
    declare @type: LicenceEntity: @Entity;
    
    @PersistenceContext
    transient EntityManager LicenceEntity.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long LicenceEntity.id;
    
    @Version
    @Column(name = "version")
    private Integer LicenceEntity.version;
    
    public Long LicenceEntity.getId() {
        return this.id;
    }
    
    public void LicenceEntity.setId(Long id) {
        this.id = id;
    }
    
    public Integer LicenceEntity.getVersion() {
        return this.version;
    }
    
    public void LicenceEntity.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void LicenceEntity.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void LicenceEntity.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            LicenceEntity attached = LicenceEntity.findLicenceEntity(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void LicenceEntity.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void LicenceEntity.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public LicenceEntity LicenceEntity.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        LicenceEntity merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager LicenceEntity.entityManager() {
        EntityManager em = new LicenceEntity().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long LicenceEntity.countLicenceEntitys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM LicenceEntity o", Long.class).getSingleResult();
    }
    
    public static List<LicenceEntity> LicenceEntity.findAllLicenceEntitys() {
        return entityManager().createQuery("SELECT o FROM LicenceEntity o", LicenceEntity.class).getResultList();
    }
    
    public static LicenceEntity LicenceEntity.findLicenceEntity(Long id) {
        if (id == null) return null;
        return entityManager().find(LicenceEntity.class, id);
    }
    
    public static List<LicenceEntity> LicenceEntity.findLicenceEntityEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM LicenceEntity o", LicenceEntity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
