// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.adorsys.adpharma.domain.LigneCmdClient;

privileged aspect LigneCmdClient_Roo_Json {
    
    public String LigneCmdClient.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static LigneCmdClient LigneCmdClient.fromJsonToLigneCmdClient(String json) {
        return new JSONDeserializer<LigneCmdClient>().use(null, LigneCmdClient.class).deserialize(json);
    }
    
    public static String LigneCmdClient.toJsonArray(Collection<LigneCmdClient> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<LigneCmdClient> LigneCmdClient.fromJsonArrayToLigneCmdClients(String json) {
        return new JSONDeserializer<List<LigneCmdClient>>().use(null, ArrayList.class).use("values", LigneCmdClient.class).deserialize(json);
    }
    
}
