// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import org.adorsys.adpharma.domain.CommandeClient;
import org.adorsys.adpharma.domain.LigneApprovisionement;

privileged aspect LigneCmdClient_Roo_JavaBean {
    
    public CommandeClient LigneCmdClient.getCommande() {
        return this.commande;
    }
    
    public void LigneCmdClient.setCommande(CommandeClient commande) {
        this.commande = commande;
    }
    
    public BigInteger LigneCmdClient.getQuantiteCommande() {
        return this.quantiteCommande;
    }
    
    public void LigneCmdClient.setQuantiteCommande(BigInteger quantiteCommande) {
        this.quantiteCommande = quantiteCommande;
    }
    
    public BigInteger LigneCmdClient.getQuantiteRetourne() {
        return this.quantiteRetourne;
    }
    
    public void LigneCmdClient.setQuantiteRetourne(BigInteger quantiteRetourne) {
        this.quantiteRetourne = quantiteRetourne;
    }
    
    public Date LigneCmdClient.getDateSaisie() {
        return this.dateSaisie;
    }
    
    public void LigneCmdClient.setDateSaisie(Date dateSaisie) {
        this.dateSaisie = dateSaisie;
    }
    
    public BigDecimal LigneCmdClient.getPrixUnitaire() {
        return this.prixUnitaire;
    }
    
    public void LigneCmdClient.setPrixUnitaire(BigDecimal prixUnitaire) {
        this.prixUnitaire = prixUnitaire;
    }
    
    public BigDecimal LigneCmdClient.getRemise() {
        return this.remise;
    }
    
    public void LigneCmdClient.setRemise(BigDecimal remise) {
        this.remise = remise;
    }
    
    public BigDecimal LigneCmdClient.getTotalRemise() {
        return this.totalRemise;
    }
    
    public void LigneCmdClient.setTotalRemise(BigDecimal totalRemise) {
        this.totalRemise = totalRemise;
    }
    
    public BigDecimal LigneCmdClient.getPrixTotal() {
        return this.prixTotal;
    }
    
    public void LigneCmdClient.setPrixTotal(BigDecimal prixTotal) {
        this.prixTotal = prixTotal;
    }
    
    public String LigneCmdClient.getDesignation() {
        return this.designation;
    }
    
    public void LigneCmdClient.setDesignation(String designation) {
        this.designation = designation;
    }
    
    public String LigneCmdClient.getCip() {
        return this.cip;
    }
    
    public void LigneCmdClient.setCip(String cip) {
        this.cip = cip;
    }
    
    public String LigneCmdClient.getAgentSaisie() {
        return this.agentSaisie;
    }
    
    public void LigneCmdClient.setAgentSaisie(String agentSaisie) {
        this.agentSaisie = agentSaisie;
    }
    
    public LigneApprovisionement LigneCmdClient.getProduit() {
        return this.produit;
    }
    
    public void LigneCmdClient.setProduit(LigneApprovisionement produit) {
        this.produit = produit;
    }
    
    public String LigneCmdClient.getCipM() {
        return this.cipM;
    }
    
    public void LigneCmdClient.setCipM(String cipM) {
        this.cipM = cipM;
    }
    
}
