// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import org.adorsys.adpharma.domain.CommandeClient;
import org.adorsys.adpharma.domain.LigneCmdClient;

privileged aspect LigneCmdClient_Roo_Finder {
    
    public static TypedQuery<LigneCmdClient> LigneCmdClient.findLigneCmdClientsByCipEquals(String cip) {
        if (cip == null || cip.length() == 0) throw new IllegalArgumentException("The cip argument is required");
        EntityManager em = LigneCmdClient.entityManager();
        TypedQuery<LigneCmdClient> q = em.createQuery("SELECT o FROM LigneCmdClient AS o WHERE o.cip = :cip", LigneCmdClient.class);
        q.setParameter("cip", cip);
        return q;
    }
    
    public static TypedQuery<LigneCmdClient> LigneCmdClient.findLigneCmdClientsByCipMEqualsAndCommande(String cipM, CommandeClient commande) {
        if (cipM == null || cipM.length() == 0) throw new IllegalArgumentException("The cipM argument is required");
        if (commande == null) throw new IllegalArgumentException("The commande argument is required");
        EntityManager em = LigneCmdClient.entityManager();
        TypedQuery<LigneCmdClient> q = em.createQuery("SELECT o FROM LigneCmdClient AS o WHERE o.cipM = :cipM  AND o.commande = :commande", LigneCmdClient.class);
        q.setParameter("cipM", cipM);
        q.setParameter("commande", commande);
        return q;
    }
    
}
