// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import org.adorsys.adpharma.domain.Inventaire;
import org.adorsys.adpharma.domain.Produit;

privileged aspect LigneInventaire_Roo_JavaBean {
    
    public BigInteger LigneInventaire.getQteEnStock() {
        return this.qteEnStock;
    }
    
    public void LigneInventaire.setQteEnStock(BigInteger qteEnStock) {
        this.qteEnStock = qteEnStock;
    }
    
    public BigInteger LigneInventaire.getQteReel() {
        return this.qteReel;
    }
    
    public void LigneInventaire.setQteReel(BigInteger qteReel) {
        this.qteReel = qteReel;
    }
    
    public BigInteger LigneInventaire.getEcart() {
        return this.ecart;
    }
    
    public void LigneInventaire.setEcart(BigInteger ecart) {
        this.ecart = ecart;
    }
    
    public BigDecimal LigneInventaire.getPrixUnitaire() {
        return this.prixUnitaire;
    }
    
    public void LigneInventaire.setPrixUnitaire(BigDecimal prixUnitaire) {
        this.prixUnitaire = prixUnitaire;
    }
    
    public BigDecimal LigneInventaire.getPrixTotal() {
        return this.prixTotal;
    }
    
    public void LigneInventaire.setPrixTotal(BigDecimal prixTotal) {
        this.prixTotal = prixTotal;
    }
    
    public String LigneInventaire.getAgentSaisie() {
        return this.agentSaisie;
    }
    
    public void LigneInventaire.setAgentSaisie(String agentSaisie) {
        this.agentSaisie = agentSaisie;
    }
    
    public Inventaire LigneInventaire.getInventaire() {
        return this.inventaire;
    }
    
    public void LigneInventaire.setInventaire(Inventaire inventaire) {
        this.inventaire = inventaire;
    }
    
    public Date LigneInventaire.getDateSaisie() {
        return this.dateSaisie;
    }
    
    public void LigneInventaire.setDateSaisie(Date dateSaisie) {
        this.dateSaisie = dateSaisie;
    }
    
    public Produit LigneInventaire.getProduit() {
        return this.produit;
    }
    
    public void LigneInventaire.setProduit(Produit produit) {
        this.produit = produit;
    }
    
}
