// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.LigneCmdFournisseur;

privileged aspect LigneCmdFournisseur_Roo_Entity {
    
    declare @type: LigneCmdFournisseur: @Entity(name = "LigneCmdFournisseur");
    
    declare @type: LigneCmdFournisseur: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long LigneCmdFournisseur.countLigneCmdFournisseurs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM LigneCmdFournisseur o", Long.class).getSingleResult();
    }
    
    public static List<LigneCmdFournisseur> LigneCmdFournisseur.findAllLigneCmdFournisseurs() {
        return entityManager().createQuery("SELECT o FROM LigneCmdFournisseur o", LigneCmdFournisseur.class).getResultList();
    }
    
    public static LigneCmdFournisseur LigneCmdFournisseur.findLigneCmdFournisseur(Long id) {
        if (id == null) return null;
        return entityManager().find(LigneCmdFournisseur.class, id);
    }
    
    public static List<LigneCmdFournisseur> LigneCmdFournisseur.findLigneCmdFournisseurEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM LigneCmdFournisseur o", LigneCmdFournisseur.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
