// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.LigneFacture;

privileged aspect LigneFacture_Roo_Entity {
    
    declare @type: LigneFacture: @Entity(name = "LigneFacture");
    
    declare @type: LigneFacture: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long LigneFacture.countLigneFactures() {
        return entityManager().createQuery("SELECT COUNT(o) FROM LigneFacture o", Long.class).getSingleResult();
    }
    
    public static List<LigneFacture> LigneFacture.findAllLigneFactures() {
        return entityManager().createQuery("SELECT o FROM LigneFacture o", LigneFacture.class).getResultList();
    }
    
    public static LigneFacture LigneFacture.findLigneFacture(Long id) {
        if (id == null) return null;
        return entityManager().find(LigneFacture.class, id);
    }
    
    public static List<LigneFacture> LigneFacture.findLigneFactureEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM LigneFacture o", LigneFacture.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
