// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.LigneCmdClient;

privileged aspect LigneCmdClient_Roo_Entity {
    
    declare @type: LigneCmdClient: @Entity(name = "LigneCmdClient");
    
    declare @type: LigneCmdClient: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long LigneCmdClient.countLigneCmdClients() {
        return entityManager().createQuery("SELECT COUNT(o) FROM LigneCmdClient o", Long.class).getSingleResult();
    }
    
    public static List<LigneCmdClient> LigneCmdClient.findAllLigneCmdClients() {
        return entityManager().createQuery("SELECT o FROM LigneCmdClient o", LigneCmdClient.class).getResultList();
    }
    
    public static LigneCmdClient LigneCmdClient.findLigneCmdClient(Long id) {
        if (id == null) return null;
        return entityManager().find(LigneCmdClient.class, id);
    }
    
    public static List<LigneCmdClient> LigneCmdClient.findLigneCmdClientEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM LigneCmdClient o", LigneCmdClient.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
