// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.util.Date;
import java.util.List;
import org.adorsys.adpharma.domain.Client;
import org.adorsys.adpharma.domain.EtatDette;
import org.adorsys.adpharma.domain.ListingEtatDette;

privileged aspect ListingEtatDette_Roo_JavaBean {
    
    public Boolean ListingEtatDette.getToutLesClients() {
        return this.toutLesClients;
    }
    
    public void ListingEtatDette.setToutLesClients(Boolean toutLesClients) {
        this.toutLesClients = toutLesClients;
    }
    
    public Client ListingEtatDette.getClient() {
        return this.client;
    }
    
    public void ListingEtatDette.setClient(Client client) {
        this.client = client;
    }
    
    public List<Client> ListingEtatDette.getClients() {
        return this.clients;
    }
    
    public void ListingEtatDette.setClients(List<Client> clients) {
        this.clients = clients;
    }
    
    public Date ListingEtatDette.getDate() {
        return this.date;
    }
    
    public void ListingEtatDette.setDate(Date date) {
        this.date = date;
    }
    
    public Boolean ListingEtatDette.getAvoir() {
        return this.avoir;
    }
    
    public void ListingEtatDette.setAvoir(Boolean avoir) {
        this.avoir = avoir;
    }
    
    public List<EtatDette> ListingEtatDette.getEtatDettes() {
        return this.EtatDettes;
    }
    
    public void ListingEtatDette.setEtatDettes(List<EtatDette> EtatDettes) {
        this.EtatDettes = EtatDettes;
    }
    
}
