// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import org.adorsys.adpharma.domain.ModeConditionement;

privileged aspect ModeConditionement_Roo_JavaBean {
    
    public String ModeConditionement.getLibelle() {
        return this.libelle;
    }
    
    public void ModeConditionement.setLibelle(String libelle) {
        this.libelle = libelle;
    }
    
    public String ModeConditionement.getLibelleCourt() {
        return this.libelleCourt;
    }
    
    public void ModeConditionement.setLibelleCourt(String libelleCourt) {
        this.libelleCourt = libelleCourt;
    }
    
}
