// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.ModeConditionement;

privileged aspect ModeConditionement_Roo_Entity {
    
    declare @type: ModeConditionement: @Entity(name = "ModeConditionement");
    
    declare @type: ModeConditionement: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long ModeConditionement.countModeConditionements() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ModeConditionement o", Long.class).getSingleResult();
    }
    
    public static List<ModeConditionement> ModeConditionement.findAllModeConditionements() {
        return entityManager().createQuery("SELECT o FROM ModeConditionement o", ModeConditionement.class).getResultList();
    }
    
    public static ModeConditionement ModeConditionement.findModeConditionement(Long id) {
        if (id == null) return null;
        return entityManager().find(ModeConditionement.class, id);
    }
    
    public static List<ModeConditionement> ModeConditionement.findModeConditionementEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ModeConditionement o", ModeConditionement.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
