// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import java.util.Date;
import org.adorsys.adpharma.domain.Caisse;
import org.adorsys.adpharma.domain.OperationCaisse;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.TypeOpCaisse;
import org.adorsys.adpharma.domain.TypePaiement;

privileged aspect OperationCaisse_Roo_JavaBean {
    
    public String OperationCaisse.getOpNumber() {
        return this.opNumber;
    }
    
    public void OperationCaisse.setOpNumber(String opNumber) {
        this.opNumber = opNumber;
    }
    
    public Caisse OperationCaisse.getCaisse() {
        return this.caisse;
    }
    
    public void OperationCaisse.setCaisse(Caisse caisse) {
        this.caisse = caisse;
    }
    
    public PharmaUser OperationCaisse.getOperateur() {
        return this.operateur;
    }
    
    public void OperationCaisse.setOperateur(PharmaUser operateur) {
        this.operateur = operateur;
    }
    
    public Date OperationCaisse.getDateOperation() {
        return this.dateOperation;
    }
    
    public void OperationCaisse.setDateOperation(Date dateOperation) {
        this.dateOperation = dateOperation;
    }
    
    public TypeOpCaisse OperationCaisse.getTypeOperation() {
        return this.typeOperation;
    }
    
    public void OperationCaisse.setTypeOperation(TypeOpCaisse typeOperation) {
        this.typeOperation = typeOperation;
    }
    
    public TypePaiement OperationCaisse.getModePaiement() {
        return this.modePaiement;
    }
    
    public void OperationCaisse.setModePaiement(TypePaiement modePaiement) {
        this.modePaiement = modePaiement;
    }
    
    public BigDecimal OperationCaisse.getMontant() {
        return this.montant;
    }
    
    public void OperationCaisse.setMontant(BigDecimal montant) {
        this.montant = montant;
    }
    
    public String OperationCaisse.getRaisonOperation() {
        return this.raisonOperation;
    }
    
    public void OperationCaisse.setRaisonOperation(String raisonOperation) {
        this.raisonOperation = raisonOperation;
    }
    
    public String OperationCaisse.getNote() {
        return this.note;
    }
    
    public void OperationCaisse.setNote(String note) {
        this.note = note;
    }
    
}
