// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;

privileged aspect OperationCaisse_Roo_ToString {
    
    public String OperationCaisse.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Caisse: ").append(getCaisse()).append(", ");
        sb.append("DateOperation: ").append(getDateOperation()).append(", ");
        sb.append("FootPrint: ").append(getFootPrint()).append(", ");
        sb.append("GiveTo: ").append(getGiveTo()).append(", ");
        sb.append("Havenumber: ").append(getHavenumber()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("ModePaiement: ").append(getModePaiement()).append(", ");
        sb.append("Montant: ").append(getMontant()).append(", ");
        sb.append("Note: ").append(getNote()).append(", ");
        sb.append("OpNumber: ").append(getOpNumber()).append(", ");
        sb.append("Operateur: ").append(getOperateur()).append(", ");
        sb.append("OrderBy: ").append(getOrderBy()).append(", ");
        sb.append("RaisonOperation: ").append(getRaisonOperation()).append(", ");
        sb.append("TypeOperation: ").append(getTypeOperation()).append(", ");
        sb.append("Version: ").append(getVersion());
        return sb.toString();
    }
    
}
