// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import org.adorsys.adpharma.domain.OperationCaisse;
import org.adorsys.adpharma.domain.TypeOpCaisse;

privileged aspect OperationCaisse_Roo_Finder {
    
    public static TypedQuery<OperationCaisse> OperationCaisse.findOperationCaissesByTypeOperation(TypeOpCaisse typeOperation) {
        if (typeOperation == null) throw new IllegalArgumentException("The typeOperation argument is required");
        EntityManager em = OperationCaisse.entityManager();
        TypedQuery<OperationCaisse> q = em.createQuery("SELECT o FROM OperationCaisse AS o WHERE o.typeOperation = :typeOperation", OperationCaisse.class);
        q.setParameter("typeOperation", typeOperation);
        return q;
    }
    
}
