// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.Ordonnancier;

privileged aspect Ordonnancier_Roo_Entity {
    
    declare @type: Ordonnancier: @Entity(name = "Ordonnancier");
    
    declare @type: Ordonnancier: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long Ordonnancier.countOrdonnanciers() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Ordonnancier o", Long.class).getSingleResult();
    }
    
    public static List<Ordonnancier> Ordonnancier.findAllOrdonnanciers() {
        return entityManager().createQuery("SELECT o FROM Ordonnancier o", Ordonnancier.class).getResultList();
    }
    
    public static Ordonnancier Ordonnancier.findOrdonnancier(Long id) {
        if (id == null) return null;
        return entityManager().find(Ordonnancier.class, id);
    }
    
}
