// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import java.util.Date;
import org.adorsys.adpharma.domain.CommandeClient;

privileged aspect Ordonnancier_Roo_JavaBean {
    
    public String Ordonnancier.getPrescripteur() {
        return this.Prescripteur;
    }
    
    public void Ordonnancier.setPrescripteur(String Prescripteur) {
        this.Prescripteur = Prescripteur;
    }
    
    public String Ordonnancier.getHospital() {
        return this.hospital;
    }
    
    public void Ordonnancier.setHospital(String hospital) {
        this.hospital = hospital;
    }
    
    public String Ordonnancier.getNomDuPatient() {
        return this.nomDuPatient;
    }
    
    public void Ordonnancier.setNomDuPatient(String nomDuPatient) {
        this.nomDuPatient = nomDuPatient;
    }
    
    public String Ordonnancier.getVendeur() {
        return this.vendeur;
    }
    
    public void Ordonnancier.setVendeur(String vendeur) {
        this.vendeur = vendeur;
    }
    
    public String Ordonnancier.getOrdNumber() {
        return this.ordNumber;
    }
    
    public void Ordonnancier.setOrdNumber(String ordNumber) {
        this.ordNumber = ordNumber;
    }
    
    public CommandeClient Ordonnancier.getCommande() {
        return this.commande;
    }
    
    public void Ordonnancier.setCommande(CommandeClient commande) {
        this.commande = commande;
    }
    
    public Date Ordonnancier.getDatePrescription() {
        return this.datePrescription;
    }
    
    public void Ordonnancier.setDatePrescription(Date datePrescription) {
        this.datePrescription = datePrescription;
    }
    
    public Date Ordonnancier.getDateSaisie() {
        return this.dateSaisie;
    }
    
    public void Ordonnancier.setDateSaisie(Date dateSaisie) {
        this.dateSaisie = dateSaisie;
    }
    
}
