// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.Paiement;

privileged aspect Paiement_Roo_Entity {
    
    declare @type: Paiement: @Entity(name = "Paiement");
    
    declare @type: Paiement: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long Paiement.countPaiements() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Paiement o", Long.class).getSingleResult();
    }
    
    public static Paiement Paiement.findPaiement(Long id) {
        if (id == null) return null;
        return entityManager().find(Paiement.class, id);
    }
    
}
