// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import org.adorsys.adpharma.domain.PasswordReset;

privileged aspect PasswordReset_Roo_JavaBean {
    
    public String PasswordReset.getUserName() {
        return this.userName;
    }
    
    public void PasswordReset.setUserName(String userName) {
        this.userName = userName;
    }
    
    public String PasswordReset.getCurrentPassword() {
        return this.currentPassword;
    }
    
    public void PasswordReset.setCurrentPassword(String currentPassword) {
        this.currentPassword = currentPassword;
    }
    
    public String PasswordReset.getNewPassword() {
        return this.newPassword;
    }
    
    public void PasswordReset.setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }
    
    public String PasswordReset.getConfirmNewPassword() {
        return this.confirmNewPassword;
    }
    
    public void PasswordReset.setConfirmNewPassword(String confirmNewPassword) {
        this.confirmNewPassword = confirmNewPassword;
    }
    
}
