// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;

privileged aspect PharmaUser_Roo_Entity {
    
    declare @type: PharmaUser: @Entity(name = "PharmaUser");
    
    declare @type: PharmaUser: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long PharmaUser.countPharmaUsers() {
        return entityManager().createQuery("SELECT COUNT(o) FROM PharmaUser o", Long.class).getSingleResult();
    }
    
}
