// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import org.adorsys.adpharma.domain.Genre;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.RoleName;
import org.adorsys.adpharma.domain.Site;

privileged aspect PharmaUser_Roo_JavaBean {
    
    public String PharmaUser.getUserNumber() {
        return this.userNumber;
    }
    
    public void PharmaUser.setUserNumber(String userNumber) {
        this.userNumber = userNumber;
    }
    
    public Genre PharmaUser.getGender() {
        return this.gender;
    }
    
    public void PharmaUser.setGender(Genre gender) {
        this.gender = gender;
    }
    
    public String PharmaUser.getUserName() {
        return this.userName;
    }
    
    public void PharmaUser.setUserName(String userName) {
        this.userName = userName;
    }
    
    public String PharmaUser.getFirstName() {
        return this.firstName;
    }
    
    public void PharmaUser.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String PharmaUser.getLastName() {
        return this.lastName;
    }
    
    public void PharmaUser.setLastName(String lastName) {
        this.lastName = lastName;
    }
    
    public String PharmaUser.getFullName() {
        return this.fullName;
    }
    
    public void PharmaUser.setFullName(String fullName) {
        this.fullName = fullName;
    }
    
    public String PharmaUser.getPassword() {
        return this.password;
    }
    
    public void PharmaUser.setPassword(String password) {
        this.password = password;
    }
    
    public Set<RoleName> PharmaUser.getRoleNames() {
        return this.roleNames;
    }
    
    public void PharmaUser.setRoleNames(Set<RoleName> roleNames) {
        this.roleNames = roleNames;
    }
    
    public String PharmaUser.getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void PharmaUser.setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    
    public Date PharmaUser.getAccountExpiration() {
        return this.accountExpiration;
    }
    
    public void PharmaUser.setAccountExpiration(Date accountExpiration) {
        this.accountExpiration = accountExpiration;
    }
    
    public boolean PharmaUser.isDisableLogin() {
        return this.disableLogin;
    }
    
    public void PharmaUser.setDisableLogin(boolean disableLogin) {
        this.disableLogin = disableLogin;
    }
    
    public boolean PharmaUser.isAccountLocked() {
        return this.accountLocked;
    }
    
    public void PharmaUser.setAccountLocked(boolean accountLocked) {
        this.accountLocked = accountLocked;
    }
    
    public Date PharmaUser.getCredentialExpiration() {
        return this.credentialExpiration;
    }
    
    public void PharmaUser.setCredentialExpiration(Date credentialExpiration) {
        this.credentialExpiration = credentialExpiration;
    }
    
    public String PharmaUser.getAdresse() {
        return this.adresse;
    }
    
    public void PharmaUser.setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
    public String PharmaUser.getEmail() {
        return this.email;
    }
    
    public void PharmaUser.setEmail(String email) {
        this.email = email;
    }
    
    public Site PharmaUser.getOffice() {
        return this.office;
    }
    
    public void PharmaUser.setOffice(Site office) {
        this.office = office;
    }
    
    public BigDecimal PharmaUser.getTauxRemise() {
        return this.tauxRemise;
    }
    
    public void PharmaUser.setTauxRemise(BigDecimal tauxRemise) {
        this.tauxRemise = tauxRemise;
    }
    
    public String PharmaUser.getSaleKey() {
        return this.saleKey;
    }
    
    public void PharmaUser.setSaleKey(String saleKey) {
        this.saleKey = saleKey;
    }
    
}
