// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.adorsys.adpharma.domain.PharmaUser;

privileged aspect PharmaUser_Roo_Json {
    
    public String PharmaUser.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static PharmaUser PharmaUser.fromJsonToPharmaUser(String json) {
        return new JSONDeserializer<PharmaUser>().use(null, PharmaUser.class).deserialize(json);
    }
    
    public static String PharmaUser.toJsonArray(Collection<PharmaUser> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<PharmaUser> PharmaUser.fromJsonArrayToPharmaUsers(String json) {
        return new JSONDeserializer<List<PharmaUser>>().use(null, ArrayList.class).use("values", PharmaUser.class).deserialize(json);
    }
    
}
