// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import org.adorsys.adpharma.domain.PharmaUser;

privileged aspect PharmaUser_Roo_Finder {
    
    public static TypedQuery<PharmaUser> PharmaUser.findPharmaUsersBySaleKeyEquals(String saleKey) {
        if (saleKey == null || saleKey.length() == 0) throw new IllegalArgumentException("The saleKey argument is required");
        EntityManager em = PharmaUser.entityManager();
        TypedQuery<PharmaUser> q = em.createQuery("SELECT o FROM PharmaUser AS o WHERE o.saleKey = :saleKey", PharmaUser.class);
        q.setParameter("saleKey", saleKey);
        return q;
    }
    
}
