// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.Produit;

privileged aspect Produit_Roo_Entity {
    
    declare @type: Produit: @Entity(name = "Produit");
    
    declare @type: Produit: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long Produit.countProduits() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Produit o", Long.class).getSingleResult();
    }
    
    public static List<Produit> Produit.findAllProduits() {
        return entityManager().createQuery("SELECT o FROM Produit o", Produit.class).getResultList();
    }
    
    public static Produit Produit.findProduit(Long id) {
        if (id == null) return null;
        return entityManager().find(Produit.class, id);
    }
    
}
