// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.adorsys.adpharma.domain.Produit;

privileged aspect Produit_Roo_Json {
    
    public String Produit.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Produit Produit.fromJsonToProduit(String json) {
        return new JSONDeserializer<Produit>().use(null, Produit.class).deserialize(json);
    }
    
    public static String Produit.toJsonArray(Collection<Produit> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Produit> Produit.fromJsonArrayToProduits(String json) {
        return new JSONDeserializer<List<Produit>>().use(null, ArrayList.class).use("values", Produit.class).deserialize(json);
    }
    
}
