package org.adorsys.adpharma.domain;


public enum RoleName {

    ROLE_ADMIN, ROLE_STOCKER, ROLE_CASHIER, ROLE_SITE_MANAGER, ROLE_VENDEUR,ROLE_SUPER_ADMIN , ROLE_OPEN_SALE_SESSION,ROLE_INVENTAIRE,ROLE_GESTION_DETTE,ROLE_RETOUR_PRODUIT
}
