// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Boolean;
import java.math.BigDecimal;
import java.math.BigInteger;
import org.adorsys.adpharma.domain.TypeVente;

privileged aspect SalesConfiguration_Roo_JavaBean {
    
    public BigInteger SalesConfiguration.getMinValue() {
        return this.minValue;
    }
    
    public void SalesConfiguration.setMinValue(BigInteger minValue) {
        this.minValue = minValue;
    }
    
    public BigInteger SalesConfiguration.getMaxValue() {
        return this.maxValue;
    }
    
    public void SalesConfiguration.setMaxValue(BigInteger maxValue) {
        this.maxValue = maxValue;
    }
    
    public BigDecimal SalesConfiguration.getTauxReduction() {
        return this.tauxReduction;
    }
    
    public void SalesConfiguration.setTauxReduction(BigDecimal tauxReduction) {
        this.tauxReduction = tauxReduction;
    }
    
    public Boolean SalesConfiguration.getActiveConfig() {
        return this.activeConfig;
    }
    
    public void SalesConfiguration.setActiveConfig(Boolean activeConfig) {
        this.activeConfig = activeConfig;
    }
    
    public TypeVente SalesConfiguration.getTypeVente() {
        return this.typeVente;
    }
    
    public void SalesConfiguration.setTypeVente(TypeVente typeVente) {
        this.typeVente = typeVente;
    }
    
}
