// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.Site;

privileged aspect Site_Roo_Entity {
    
    declare @type: Site: @Entity(name = "Site");
    
    declare @type: Site: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long Site.countSites() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Site o", Long.class).getSingleResult();
    }
    
    public static List<Site> Site.findAllSites() {
        return entityManager().createQuery("SELECT o FROM Site o", Site.class).getResultList();
    }
    
    public static Site Site.findSite(Long id) {
        if (id == null) return null;
        return entityManager().find(Site.class, id);
    }
    
    public static List<Site> Site.findSiteEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Site o", Site.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
