// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import org.adorsys.adpharma.domain.Site;

privileged aspect Site_Roo_JavaBean {
    
    public String Site.getDisplayName() {
        return this.displayName;
    }
    
    public void Site.setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    
    public String Site.getAdresse() {
        return this.adresse;
    }
    
    public void Site.setAdresse(String adresse) {
        this.adresse = adresse;
    }
    
    public String Site.getVille() {
        return this.ville;
    }
    
    public void Site.setVille(String ville) {
        this.ville = ville;
    }
    
    public String Site.getPays() {
        return this.Pays;
    }
    
    public void Site.setPays(String Pays) {
        this.Pays = Pays;
    }
    
    public String Site.getSiteNumber() {
        return this.siteNumber;
    }
    
    public void Site.setSiteNumber(String siteNumber) {
        this.siteNumber = siteNumber;
    }
    
    public String Site.getPhone() {
        return this.phone;
    }
    
    public void Site.setPhone(String phone) {
        this.phone = phone;
    }
    
    public String Site.getSiteManager() {
        return this.siteManager;
    }
    
    public void Site.setSiteManager(String siteManager) {
        this.siteManager = siteManager;
    }
    
    public String Site.getEmail() {
        return this.email;
    }
    
    public void Site.setEmail(String email) {
        this.email = email;
    }
    
    public String Site.getSiteInternet() {
        return this.siteInternet;
    }
    
    public void Site.setSiteInternet(String siteInternet) {
        this.siteInternet = siteInternet;
    }
    
    public String Site.getMobile() {
        return this.mobile;
    }
    
    public void Site.setMobile(String mobile) {
        this.mobile = mobile;
    }
    
    public String Site.getFax() {
        return this.fax;
    }
    
    public void Site.setFax(String fax) {
        this.fax = fax;
    }
    
    public String Site.getNumeroRegistre() {
        return this.numeroRegistre;
    }
    
    public void Site.setNumeroRegistre(String numeroRegistre) {
        this.numeroRegistre = numeroRegistre;
    }
    
    public String Site.getMessageTiket() {
        return this.messageTiket;
    }
    
    public void Site.setMessageTiket(String messageTiket) {
        this.messageTiket = messageTiket;
    }
    
}
