// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.SousFamilleProduit;

privileged aspect SousFamilleProduit_Roo_Entity {
    
    declare @type: SousFamilleProduit: @Entity(name = "SousFamilleProduit");
    
    declare @type: SousFamilleProduit: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long SousFamilleProduit.countSousFamilleProduits() {
        return entityManager().createQuery("SELECT COUNT(o) FROM SousFamilleProduit o", Long.class).getSingleResult();
    }
    
    public static List<SousFamilleProduit> SousFamilleProduit.findAllSousFamilleProduits() {
        return entityManager().createQuery("SELECT o FROM SousFamilleProduit o", SousFamilleProduit.class).getResultList();
    }
    
    public static SousFamilleProduit SousFamilleProduit.findSousFamilleProduit(Long id) {
        if (id == null) return null;
        return entityManager().find(SousFamilleProduit.class, id);
    }
    
    public static List<SousFamilleProduit> SousFamilleProduit.findSousFamilleProduitEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM SousFamilleProduit o", SousFamilleProduit.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
