// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;
import org.adorsys.adpharma.domain.FamilleProduit;

privileged aspect SousFamilleProduit_Roo_JavaBean {
    
    public String SousFamilleProduit.getSousFamilleNumber() {
        return this.sousFamilleNumber;
    }
    
    public void SousFamilleProduit.setSousFamilleNumber(String sousFamilleNumber) {
        this.sousFamilleNumber = sousFamilleNumber;
    }
    
    public String SousFamilleProduit.getLibelleSousFamille() {
        return this.libelleSousFamille;
    }
    
    public void SousFamilleProduit.setLibelleSousFamille(String libelleSousFamille) {
        this.libelleSousFamille = libelleSousFamille;
    }
    
    public String SousFamilleProduit.getLibelleCourt() {
        return this.libelleCourt;
    }
    
    public void SousFamilleProduit.setLibelleCourt(String libelleCourt) {
        this.libelleCourt = libelleCourt;
    }
    
    public String SousFamilleProduit.getNote() {
        return this.note;
    }
    
    public void SousFamilleProduit.setNote(String note) {
        this.note = note;
    }
    
    public FamilleProduit SousFamilleProduit.getFamille() {
        return this.famille;
    }
    
    public void SousFamilleProduit.setFamille(FamilleProduit famille) {
        this.famille = famille;
    }
    
}
