// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.String;

privileged aspect SousFamilleProduit_Roo_ToString {
    
    public String SousFamilleProduit.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Archived: ").append(getArchived()).append(", ");
        sb.append("Famille: ").append(getFamille()).append(", ");
        sb.append("FootPrint: ").append(getFootPrint()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("LibelleCourt: ").append(getLibelleCourt()).append(", ");
        sb.append("LibelleSousFamille: ").append(getLibelleSousFamille()).append(", ");
        sb.append("Note: ").append(getNote()).append(", ");
        sb.append("SousFamilleNumber: ").append(getSousFamilleNumber()).append(", ");
        sb.append("Version: ").append(getVersion());
        return sb.toString();
    }
    
}
