// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.math.BigDecimal;
import org.adorsys.adpharma.domain.TauxMarge;

privileged aspect TauxMarge_Roo_JavaBean {
    
    public String TauxMarge.getMargeNumber() {
        return this.margeNumber;
    }
    
    public void TauxMarge.setMargeNumber(String margeNumber) {
        this.margeNumber = margeNumber;
    }
    
    public BigDecimal TauxMarge.getMargeValue() {
        return this.margeValue;
    }
    
    public void TauxMarge.setMargeValue(BigDecimal margeValue) {
        this.margeValue = margeValue;
    }
    
    public Boolean TauxMarge.getValide() {
        return this.valide;
    }
    
    public void TauxMarge.setValide(Boolean valide) {
        this.valide = valide;
    }
    
}
