// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.TauxMarge;

privileged aspect TauxMarge_Roo_Entity {
    
    declare @type: TauxMarge: @Entity(name = "TauxMarge");
    
    declare @type: TauxMarge: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long TauxMarge.countTauxMarges() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TauxMarge o", Long.class).getSingleResult();
    }
    
    public static List<TauxMarge> TauxMarge.findAllTauxMarges() {
        return entityManager().createQuery("SELECT o FROM TauxMarge o", TauxMarge.class).getResultList();
    }
    
    public static TauxMarge TauxMarge.findTauxMarge(Long id) {
        if (id == null) return null;
        return entityManager().find(TauxMarge.class, id);
    }
    
    public static List<TauxMarge> TauxMarge.findTauxMargeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TauxMarge o", TauxMarge.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
