// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import org.adorsys.adpharma.domain.TransformationProduit;

privileged aspect TransformationProduit_Roo_Json {
    
    public String TransformationProduit.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static TransformationProduit TransformationProduit.fromJsonToTransformationProduit(String json) {
        return new JSONDeserializer<TransformationProduit>().use(null, TransformationProduit.class).deserialize(json);
    }
    
    public static String TransformationProduit.toJsonArray(Collection<TransformationProduit> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<TransformationProduit> TransformationProduit.fromJsonArrayToTransformationProduits(String json) {
        return new JSONDeserializer<List<TransformationProduit>>().use(null, ArrayList.class).use("values", TransformationProduit.class).deserialize(json);
    }
    
}
