// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import org.adorsys.adpharma.domain.Produit;
import org.adorsys.adpharma.domain.TransformationProduit;

privileged aspect TransformationProduit_Roo_Finder {
    
    public static TypedQuery<TransformationProduit> TransformationProduit.findTransformationProduitsByProduitOrigine(Produit produitOrigine) {
        if (produitOrigine == null) throw new IllegalArgumentException("The produitOrigine argument is required");
        EntityManager em = TransformationProduit.entityManager();
        TypedQuery<TransformationProduit> q = em.createQuery("SELECT o FROM TransformationProduit AS o WHERE o.produitOrigine = :produitOrigine", TransformationProduit.class);
        q.setParameter("produitOrigine", produitOrigine);
        return q;
    }
    
    public static TypedQuery<TransformationProduit> TransformationProduit.findTransformationProduitsByProduitOrigineAndProduitCible(Produit produitOrigine, Produit produitCible) {
        if (produitOrigine == null) throw new IllegalArgumentException("The produitOrigine argument is required");
        if (produitCible == null) throw new IllegalArgumentException("The produitCible argument is required");
        EntityManager em = TransformationProduit.entityManager();
        TypedQuery<TransformationProduit> q = em.createQuery("SELECT o FROM TransformationProduit AS o WHERE o.produitOrigine = :produitOrigine AND o.produitCible = :produitCible", TransformationProduit.class);
        q.setParameter("produitOrigine", produitOrigine);
        q.setParameter("produitCible", produitCible);
        return q;
    }
    
}
