// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain;

import java.lang.Long;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import org.adorsys.adpharma.domain.TVA;

privileged aspect TVA_Roo_Entity {
    
    declare @type: TVA: @Entity(name = "TVA");
    
    declare @type: TVA: @Inheritance(strategy = InheritanceType.TABLE_PER_CLASS);
    
    public static long TVA.countTVAS() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TVA o", Long.class).getSingleResult();
    }
    
    public static List<TVA> TVA.findAllTVAS() {
        return entityManager().createQuery("SELECT o FROM TVA o", TVA.class).getResultList();
    }
    
    public static TVA TVA.findTVA(Long id) {
        if (id == null) return null;
        return entityManager().find(TVA.class, id);
    }
    
    public static List<TVA> TVA.findTVAEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TVA o", TVA.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
