// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.beans;

import java.lang.Long;
import java.lang.String;
import java.math.BigInteger;

privileged aspect CommandeCredit_Roo_JavaBean {
    
    public Long CommandeCredit.getClientId() {
        return this.clientId;
    }
    
    public void CommandeCredit.setClientId(Long clientId) {
        this.clientId = clientId;
    }
    
    public Long CommandeCredit.getPayeurId() {
        return this.payeurId;
    }
    
    public void CommandeCredit.setPayeurId(Long payeurId) {
        this.payeurId = payeurId;
    }
    
    public String CommandeCredit.getClientName() {
        return this.clientName;
    }
    
    public void CommandeCredit.setClientName(String clientName) {
        this.clientName = clientName;
    }
    
    public String CommandeCredit.getPayeurName() {
        return this.payeurName;
    }
    
    public void CommandeCredit.setPayeurName(String payeurName) {
        this.payeurName = payeurName;
    }
    
    public boolean CommandeCredit.isVentePartiel() {
        return this.ventePartiel;
    }
    
    public void CommandeCredit.setVentePartiel(boolean ventePartiel) {
        this.ventePartiel = ventePartiel;
    }
    
    public BigInteger CommandeCredit.getTaux() {
        return this.taux;
    }
    
    public void CommandeCredit.setTaux(BigInteger taux) {
        this.taux = taux;
    }
    
}
