// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.beans;

import java.lang.Integer;
import java.math.BigInteger;

privileged aspect CourbeApprovisionnement_Roo_JavaBean {
    
    public BigInteger CourbeApprovisionnement.getPaTotal() {
        return this.paTotal;
    }
    
    public void CourbeApprovisionnement.setPaTotal(BigInteger paTotal) {
        this.paTotal = paTotal;
    }
    
    public Integer CourbeApprovisionnement.getMois() {
        return this.mois;
    }
    
    public void CourbeApprovisionnement.setMois(Integer mois) {
        this.mois = mois;
    }
    
    public Integer CourbeApprovisionnement.getAnnee() {
        return this.annee;
    }
    
    public void CourbeApprovisionnement.setAnnee(Integer annee) {
        this.annee = annee;
    }
    
}
