// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.beans;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;
import org.adorsys.adpharma.domain.PharmaUser;

privileged aspect Decaissement_Roo_JavaBean {
    
    public Date Decaissement.getDateDecaissement() {
        return this.dateDecaissement;
    }
    
    public void Decaissement.setDateDecaissement(Date dateDecaissement) {
        this.dateDecaissement = dateDecaissement;
    }
    
    public String Decaissement.getTypeDecaissement() {
        return this.typeDecaissement;
    }
    
    public void Decaissement.setTypeDecaissement(String typeDecaissement) {
        this.typeDecaissement = typeDecaissement;
    }
    
    public BigDecimal Decaissement.getMontantDecaissement() {
        return this.montantDecaissement;
    }
    
    public void Decaissement.setMontantDecaissement(BigDecimal montantDecaissement) {
        this.montantDecaissement = montantDecaissement;
    }
    
    public PharmaUser Decaissement.getOperateur() {
        return this.operateur;
    }
    
    public void Decaissement.setOperateur(PharmaUser operateur) {
        this.operateur = operateur;
    }
    
    public String Decaissement.getNumAvoir() {
        return this.numAvoir;
    }
    
    public void Decaissement.setNumAvoir(String numAvoir) {
        this.numAvoir = numAvoir;
    }
    
    public String Decaissement.getNote() {
        return this.note;
    }
    
    public void Decaissement.setNote(String note) {
        this.note = note;
    }
    
}
