// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Approvisionement;
import org.adorsys.adpharma.domain.CommandeFournisseur;
import org.adorsys.adpharma.domain.Devise;
import org.adorsys.adpharma.domain.Etat;
import org.adorsys.adpharma.domain.Filiale;
import org.adorsys.adpharma.domain.Fournisseur;
import org.adorsys.adpharma.domain.LigneApprovisionement;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.Site;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ApprovisionementController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String ApprovisionementController.create(@Valid Approvisionement approvisionement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("approvisionement", approvisionement);
            addDateTimeFormatPatterns(uiModel);
            return "approvisionements/create";
        }
        uiModel.asMap().clear();
        approvisionement.persist();
        return "redirect:/approvisionements/" + encodeUrlPathSegment(approvisionement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String ApprovisionementController.createForm(Model uiModel) {
        uiModel.addAttribute("approvisionement", new Approvisionement());
        addDateTimeFormatPatterns(uiModel);
        List dependencies = new ArrayList();
        if (Fournisseur.countFournisseurs() == 0) {
            dependencies.add(new String[]{"fournisseur", "fournisseurs"});
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "approvisionements/create";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String ApprovisionementController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("approvisionements", Approvisionement.findApprovisionementEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) Approvisionement.countApprovisionements() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("approvisionements", Approvisionement.findAllApprovisionements());
        }
        addDateTimeFormatPatterns(uiModel);
        return "approvisionements/list";
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String ApprovisionementController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("approvisionement", Approvisionement.findApprovisionement(id));
        addDateTimeFormatPatterns(uiModel);
        return "approvisionements/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String ApprovisionementController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Approvisionement.findApprovisionement(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/approvisionements";
    }
    
    void ApprovisionementController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("approvisionement_datebordereau_date_format", "dd-MM-yyyy");
        uiModel.addAttribute("approvisionement_datecommande_date_format", "dd-MM-yyyy");
        uiModel.addAttribute("approvisionement_datelivraison_date_format", "dd-MM-yyyy");
        uiModel.addAttribute("approvisionement_datereglement_date_format", "dd-MM-yyyy");
        uiModel.addAttribute("approvisionement_datecreation_date_format", "dd-MM-yyyy HH:mm");
    }
    
    String ApprovisionementController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
