// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.CategorieClient;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CategorieClientController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String CategorieClientController.create(@Valid CategorieClient categorieClient, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("categorieClient", categorieClient);
            return "categorieclients/create";
        }
        uiModel.asMap().clear();
        categorieClient.persist();
        return "redirect:/categorieclients/" + encodeUrlPathSegment(categorieClient.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String CategorieClientController.createForm(Model uiModel) {
        uiModel.addAttribute("categorieClient", new CategorieClient());
        return "categorieclients/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String CategorieClientController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("categorieclient", CategorieClient.findCategorieClient(id));
        uiModel.addAttribute("itemId", id);
        return "categorieclients/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String CategorieClientController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("categorieclients", CategorieClient.findCategorieClientEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) CategorieClient.countCategorieClients() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("categorieclients", CategorieClient.findAllCategorieClients());
        }
        return "categorieclients/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String CategorieClientController.update(@Valid CategorieClient categorieClient, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("categorieClient", categorieClient);
            return "categorieclients/update";
        }
        uiModel.asMap().clear();
        categorieClient.merge();
        return "redirect:/categorieclients/" + encodeUrlPathSegment(categorieClient.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String CategorieClientController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("categorieClient", CategorieClient.findCategorieClient(id));
        return "categorieclients/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String CategorieClientController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        CategorieClient.findCategorieClient(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/categorieclients";
    }
    
    @ModelAttribute("categorieclients")
    public Collection<CategorieClient> CategorieClientController.populateCategorieClients() {
        return CategorieClient.findAllCategorieClients();
    }
    
    String CategorieClientController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
