// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Arrays;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import org.adorsys.adpharma.domain.CategorieClient;
import org.adorsys.adpharma.domain.Client;
import org.adorsys.adpharma.domain.Genre;
import org.adorsys.adpharma.domain.TypeClient;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ClientController_Roo_Controller {
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String ClientController.createForm(Model uiModel) {
        uiModel.addAttribute("client", new Client());
        addDateTimeFormatPatterns(uiModel);
        return "clients/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String ClientController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("client", Client.findClient(id));
        uiModel.addAttribute("itemId", id);
        return "clients/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String ClientController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("clients", Client.findClientEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) Client.countClients() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("clients", Client.findAllClients());
        }
        addDateTimeFormatPatterns(uiModel);
        return "clients/list";
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String ClientController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("client", Client.findClient(id));
        addDateTimeFormatPatterns(uiModel);
        return "clients/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String ClientController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Client.findClient(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/clients";
    }
    
    @ModelAttribute("categorieclients")
    public Collection<CategorieClient> ClientController.populateCategorieClients() {
        return CategorieClient.findAllCategorieClients();
    }
    
    @ModelAttribute("genres")
    public Collection<Genre> ClientController.populateGenres() {
        return Arrays.asList(Genre.class.getEnumConstants());
    }
    
    @ModelAttribute("typeclients")
    public Collection<TypeClient> ClientController.populateTypeClients() {
        return Arrays.asList(TypeClient.class.getEnumConstants());
    }
    
    void ClientController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("client_datenaissance_date_format", "dd-MM-yyyy");
    }
    
    String ClientController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
