// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Client;
import org.adorsys.adpharma.domain.CommandeClient;
import org.adorsys.adpharma.domain.Etat;
import org.adorsys.adpharma.domain.LigneCmdClient;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.TypeCommande;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect CommandeClientController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String CommandeClientController.create(@Valid CommandeClient commandeClient, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("commandeClient", commandeClient);
            addDateTimeFormatPatterns(uiModel);
            return "commandeclients/create";
        }
        uiModel.asMap().clear();
        commandeClient.persist();
        return "redirect:/commandeclients/" + encodeUrlPathSegment(commandeClient.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String CommandeClientController.createForm(Model uiModel) {
        uiModel.addAttribute("commandeClient", new CommandeClient());
        addDateTimeFormatPatterns(uiModel);
        List dependencies = new ArrayList();
        if (Client.countClients() == 0) {
            dependencies.add(new String[]{"client", "clients"});
        }
        if (PharmaUser.countPharmaUsers() == 0) {
            dependencies.add(new String[]{"pharmauser", "pharmausers"});
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "commandeclients/create";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String CommandeClientController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("commandeclients", CommandeClient.findCommandeClientEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) CommandeClient.countCommandeClients() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("commandeclients", CommandeClient.findAllCommandeClients());
        }
        addDateTimeFormatPatterns(uiModel);
        return "commandeclients/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String CommandeClientController.update(@Valid CommandeClient commandeClient, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("commandeClient", commandeClient);
            addDateTimeFormatPatterns(uiModel);
            return "commandeclients/update";
        }
        uiModel.asMap().clear();
        commandeClient.merge();
        return "redirect:/commandeclients/" + encodeUrlPathSegment(commandeClient.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String CommandeClientController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("commandeClient", CommandeClient.findCommandeClient(id));
        addDateTimeFormatPatterns(uiModel);
        return "commandeclients/update";
    }
    
    @ModelAttribute("etats")
    public Collection<Etat> CommandeClientController.populateEtats() {
        return Arrays.asList(Etat.class.getEnumConstants());
    }
    
    @ModelAttribute("typecommandes")
    public Collection<TypeCommande> CommandeClientController.populateTypeCommandes() {
        return Arrays.asList(TypeCommande.class.getEnumConstants());
    }
    
    void CommandeClientController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("commandeClient_dateanullation_date_format", "dd-MM-yyyy HH:mm");
        uiModel.addAttribute("commandeClient_daterestoration_date_format", "dd-MM-yyyy HH:mm");
        uiModel.addAttribute("commandeClient_datecreation_date_format", "dd-MM-yyyy HH:mm");
    }
    
    String CommandeClientController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
