// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.DetteClient;
import org.adorsys.adpharma.domain.EtatCredits;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect DetteClientController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String DetteClientController.create(@Valid DetteClient detteClient, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("detteClient", detteClient);
            addDateTimeFormatPatterns(uiModel);
            return "detteclients/create";
        }
        uiModel.asMap().clear();
        detteClient.persist();
        return "redirect:/detteclients/" + encodeUrlPathSegment(detteClient.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String DetteClientController.createForm(Model uiModel) {
        uiModel.addAttribute("detteClient", new DetteClient());
        addDateTimeFormatPatterns(uiModel);
        return "detteclients/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String DetteClientController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("detteclient", DetteClient.findDetteClient(id));
        uiModel.addAttribute("itemId", id);
        return "detteclients/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String DetteClientController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("detteclients", DetteClient.findDetteClientEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) DetteClient.countDetteClients() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("detteclients", DetteClient.findAllDetteClients());
        }
        addDateTimeFormatPatterns(uiModel);
        return "detteclients/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String DetteClientController.update(@Valid DetteClient detteClient, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("detteClient", detteClient);
            addDateTimeFormatPatterns(uiModel);
            return "detteclients/update";
        }
        uiModel.asMap().clear();
        detteClient.merge();
        return "redirect:/detteclients/" + encodeUrlPathSegment(detteClient.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String DetteClientController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("detteClient", DetteClient.findDetteClient(id));
        addDateTimeFormatPatterns(uiModel);
        return "detteclients/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String DetteClientController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        DetteClient.findDetteClient(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/detteclients";
    }
    
    void DetteClientController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("detteClient_datecreation_date_format", "dd-MM-yyyy hh:mm");
        uiModel.addAttribute("detteClient_datedernierversement_date_format", "dd-MM-yyyy HH:mm");
        uiModel.addAttribute("detteClient_datepaiement_date_format", "dd-MM-yyyy HH:mm");
    }
    
    String DetteClientController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
