// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Devise;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect DeviseController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String DeviseController.create(@Valid Devise devise, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("devise", devise);
            return "devises/create";
        }
        uiModel.asMap().clear();
        devise.persist();
        return "redirect:/devises/" + encodeUrlPathSegment(devise.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String DeviseController.createForm(Model uiModel) {
        uiModel.addAttribute("devise", new Devise());
        return "devises/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String DeviseController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("devise", Devise.findDevise(id));
        uiModel.addAttribute("itemId", id);
        return "devises/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String DeviseController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("devises", Devise.findDeviseEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) Devise.countDevises() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("devises", Devise.findAllDevises());
        }
        return "devises/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String DeviseController.update(@Valid Devise devise, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("devise", devise);
            return "devises/update";
        }
        uiModel.asMap().clear();
        devise.merge();
        return "redirect:/devises/" + encodeUrlPathSegment(devise.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String DeviseController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("devise", Devise.findDevise(id));
        return "devises/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String DeviseController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Devise.findDevise(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/devises";
    }
    
    @ModelAttribute("devises")
    public Collection<Devise> DeviseController.populateDevises() {
        return Devise.findAllDevises();
    }
    
    String DeviseController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
