// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Filiale;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FilialeControler_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String FilialeControler.create(@Valid Filiale filiale, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("filiale", filiale);
            return "filiales/create";
        }
        uiModel.asMap().clear();
        filiale.persist();
        return "redirect:/filiales/" + encodeUrlPathSegment(filiale.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String FilialeControler.createForm(Model uiModel) {
        uiModel.addAttribute("filiale", new Filiale());
        return "filiales/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String FilialeControler.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("filiale", Filiale.findFiliale(id));
        uiModel.addAttribute("itemId", id);
        return "filiales/show";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String FilialeControler.update(@Valid Filiale filiale, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("filiale", filiale);
            return "filiales/update";
        }
        uiModel.asMap().clear();
        filiale.merge();
        return "redirect:/filiales/" + encodeUrlPathSegment(filiale.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String FilialeControler.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("filiale", Filiale.findFiliale(id));
        return "filiales/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String FilialeControler.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Filiale.findFiliale(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/filiales";
    }
    
    @ModelAttribute("filiales")
    public Collection<Filiale> FilialeControler.populateFiliales() {
        return Filiale.findAllFiliales();
    }
    
    String FilialeControler.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
