// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Fournisseur;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect FournisseurController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String FournisseurController.create(@Valid Fournisseur fournisseur, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("fournisseur", fournisseur);
            return "fournisseurs/create";
        }
        uiModel.asMap().clear();
        fournisseur.persist();
        return "redirect:/fournisseurs/" + encodeUrlPathSegment(fournisseur.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String FournisseurController.createForm(Model uiModel) {
        uiModel.addAttribute("fournisseur", new Fournisseur());
        return "fournisseurs/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String FournisseurController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("fournisseur", Fournisseur.findFournisseur(id));
        uiModel.addAttribute("itemId", id);
        return "fournisseurs/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String FournisseurController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("fournisseurs", Fournisseur.findFournisseurEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) Fournisseur.countFournisseurs() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("fournisseurs", Fournisseur.findAllFournisseurs());
        }
        return "fournisseurs/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String FournisseurController.update(@Valid Fournisseur fournisseur, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("fournisseur", fournisseur);
            return "fournisseurs/update";
        }
        uiModel.asMap().clear();
        fournisseur.merge();
        return "redirect:/fournisseurs/" + encodeUrlPathSegment(fournisseur.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String FournisseurController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("fournisseur", Fournisseur.findFournisseur(id));
        return "fournisseurs/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String FournisseurController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Fournisseur.findFournisseur(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/fournisseurs";
    }
    
    @ModelAttribute("fournisseurs")
    public Collection<Fournisseur> FournisseurController.populateFournisseurs() {
        return Fournisseur.findAllFournisseurs();
    }
    
    String FournisseurController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
