// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.ArrayList;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Approvisionement;
import org.adorsys.adpharma.domain.LigneApprovisionement;
import org.adorsys.adpharma.domain.Produit;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect LigneApprovisionementController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String LigneApprovisionementController.create(@Valid LigneApprovisionement ligneApprovisionement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("ligneApprovisionement", ligneApprovisionement);
            addDateTimeFormatPatterns(uiModel);
            return "ligneapprovisionements/create";
        }
        uiModel.asMap().clear();
        ligneApprovisionement.persist();
        return "redirect:/ligneapprovisionements/" + encodeUrlPathSegment(ligneApprovisionement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String LigneApprovisionementController.createForm(Model uiModel) {
        uiModel.addAttribute("ligneApprovisionement", new LigneApprovisionement());
        addDateTimeFormatPatterns(uiModel);
        List dependencies = new ArrayList();
        if (Produit.countProduits() == 0) {
            dependencies.add(new String[]{"produit", "produits"});
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "ligneapprovisionements/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String LigneApprovisionementController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("ligneapprovisionement", LigneApprovisionement.findLigneApprovisionement(id));
        uiModel.addAttribute("itemId", id);
        return "ligneapprovisionements/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String LigneApprovisionementController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findLigneApprovisionementEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) LigneApprovisionement.countLigneApprovisionements() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findAllLigneApprovisionements());
        }
        addDateTimeFormatPatterns(uiModel);
        return "ligneapprovisionements/list";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String LigneApprovisionementController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        LigneApprovisionement.findLigneApprovisionement(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/ligneapprovisionements";
    }
    
    void LigneApprovisionementController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("ligneApprovisionement_datefabrication_date_format", "dd-MM-yyyy");
        uiModel.addAttribute("ligneApprovisionement_dateperemtion_date_format", "dd-MM-yyyy");
        uiModel.addAttribute("ligneApprovisionement_datesaisie_date_format", "dd-MM-yyyy HH:mm");
    }
    
    String LigneApprovisionementController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
