// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.Inventaire;
import org.adorsys.adpharma.domain.LigneInventaire;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect LigneInventaireController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByInventaire", "form" }, method = RequestMethod.GET)
    public String LigneInventaireController.findLigneInventairesByInventaireForm(Model uiModel) {
        uiModel.addAttribute("inventaires", Inventaire.findAllInventaires());
        return "ligneinventaires/findLigneInventairesByInventaire";
    }
    
    @RequestMapping(params = "find=ByInventaire", method = RequestMethod.GET)
    public String LigneInventaireController.findLigneInventairesByInventaire(@RequestParam("inventaire") Inventaire inventaire, Model uiModel) {
        uiModel.addAttribute("ligneinventaires", LigneInventaire.findLigneInventairesByInventaire(inventaire).getResultList());
        return "ligneinventaires/list";
    }
    
}
