// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.CommandeFournisseur;
import org.adorsys.adpharma.domain.LigneCmdFournisseur;
import org.adorsys.adpharma.domain.Produit;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect LigneCmdFournisseurContoller_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String LigneCmdFournisseurContoller.create(@Valid LigneCmdFournisseur ligneCmdFournisseur, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("ligneCmdFournisseur", ligneCmdFournisseur);
            addDateTimeFormatPatterns(uiModel);
            return "lignecmdfournisseurs/create";
        }
        uiModel.asMap().clear();
        ligneCmdFournisseur.persist();
        return "redirect:/lignecmdfournisseurs/" + encodeUrlPathSegment(ligneCmdFournisseur.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String LigneCmdFournisseurContoller.createForm(Model uiModel) {
        uiModel.addAttribute("ligneCmdFournisseur", new LigneCmdFournisseur());
        addDateTimeFormatPatterns(uiModel);
        return "lignecmdfournisseurs/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String LigneCmdFournisseurContoller.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("lignecmdfournisseur", LigneCmdFournisseur.findLigneCmdFournisseur(id));
        uiModel.addAttribute("itemId", id);
        return "lignecmdfournisseurs/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String LigneCmdFournisseurContoller.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("lignecmdfournisseurs", LigneCmdFournisseur.findLigneCmdFournisseurEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) LigneCmdFournisseur.countLigneCmdFournisseurs() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("lignecmdfournisseurs", LigneCmdFournisseur.findAllLigneCmdFournisseurs());
        }
        addDateTimeFormatPatterns(uiModel);
        return "lignecmdfournisseurs/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String LigneCmdFournisseurContoller.update(@Valid LigneCmdFournisseur ligneCmdFournisseur, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("ligneCmdFournisseur", ligneCmdFournisseur);
            addDateTimeFormatPatterns(uiModel);
            return "lignecmdfournisseurs/update";
        }
        uiModel.asMap().clear();
        ligneCmdFournisseur.merge();
        return "redirect:/lignecmdfournisseurs/" + encodeUrlPathSegment(ligneCmdFournisseur.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String LigneCmdFournisseurContoller.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("ligneCmdFournisseur", LigneCmdFournisseur.findLigneCmdFournisseur(id));
        addDateTimeFormatPatterns(uiModel);
        return "lignecmdfournisseurs/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String LigneCmdFournisseurContoller.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        LigneCmdFournisseur.findLigneCmdFournisseur(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/lignecmdfournisseurs";
    }
    
    @ModelAttribute("commandefournisseurs")
    public Collection<CommandeFournisseur> LigneCmdFournisseurContoller.populateCommandeFournisseurs() {
        return CommandeFournisseur.findAllCommandeFournisseurs();
    }
    
    @ModelAttribute("lignecmdfournisseurs")
    public Collection<LigneCmdFournisseur> LigneCmdFournisseurContoller.populateLigneCmdFournisseurs() {
        return LigneCmdFournisseur.findAllLigneCmdFournisseurs();
    }
    
    @ModelAttribute("produits")
    public Collection<Produit> LigneCmdFournisseurContoller.populateProduits() {
        return Produit.findAllProduits();
    }
    
    void LigneCmdFournisseurContoller.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("ligneCmdFournisseur_datesaisie_date_format", "dd-MM-yyyy HH:mm");
    }
    
    String LigneCmdFournisseurContoller.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
