// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.CommandeClient;
import org.adorsys.adpharma.domain.LigneCmdClient;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect LigneCmdClientController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByCipEquals", "form" }, method = RequestMethod.GET)
    public String LigneCmdClientController.findLigneCmdClientsByCipEqualsForm(Model uiModel) {
        return "lignecmdclients/findLigneCmdClientsByCipEquals";
    }
    
    @RequestMapping(params = "find=ByCipEquals", method = RequestMethod.GET)
    public String LigneCmdClientController.findLigneCmdClientsByCipEquals(@RequestParam("cip") String cip, Model uiModel) {
        uiModel.addAttribute("lignecmdclients", LigneCmdClient.findLigneCmdClientsByCipEquals(cip).getResultList());
        return "lignecmdclients/list";
    }
    
    @RequestMapping(params = { "find=ByCipMEqualsAndCommande", "form" }, method = RequestMethod.GET)
    public String LigneCmdClientController.findLigneCmdClientsByCipMEqualsAndCommandeForm(Model uiModel) {
        uiModel.addAttribute("commandeclients", CommandeClient.findAllCommandeClients());
        return "lignecmdclients/findLigneCmdClientsByCipMEqualsAndCommande";
    }
    
    @RequestMapping(params = "find=ByCipMEqualsAndCommande", method = RequestMethod.GET)
    public String LigneCmdClientController.findLigneCmdClientsByCipMEqualsAndCommande(@RequestParam("cipM") String cipM, @RequestParam("commande") CommandeClient commande, Model uiModel) {
        uiModel.addAttribute("lignecmdclients", LigneCmdClient.findLigneCmdClientsByCipMEqualsAndCommande(cipM, commande).getResultList());
        return "lignecmdclients/list";
    }
    
    @RequestMapping(params = { "find=ByCommande", "form" }, method = RequestMethod.GET)
    public String LigneCmdClientController.findLigneCmdClientsByCommandeForm(Model uiModel) {
        uiModel.addAttribute("commandeclients", CommandeClient.findAllCommandeClients());
        return "lignecmdclients/findLigneCmdClientsByCommande";
    }
    
    @RequestMapping(params = "find=ByCommande", method = RequestMethod.GET)
    public String LigneCmdClientController.findLigneCmdClientsByCommande(@RequestParam("commande") CommandeClient commande, Model uiModel) {
        uiModel.addAttribute("lignecmdclients", LigneCmdClient.findLigneCmdClientsByCommande(commande).getResultList());
        return "lignecmdclients/list";
    }
    
}
