// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Facture;
import org.adorsys.adpharma.domain.LigneFacture;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect LigneFactureController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String LigneFactureController.create(@Valid LigneFacture ligneFacture, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("ligneFacture", ligneFacture);
            return "lignefactures/create";
        }
        uiModel.asMap().clear();
        ligneFacture.persist();
        return "redirect:/lignefactures/" + encodeUrlPathSegment(ligneFacture.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String LigneFactureController.createForm(Model uiModel) {
        uiModel.addAttribute("ligneFacture", new LigneFacture());
        List dependencies = new ArrayList();
        if (Facture.countFactures() == 0) {
            dependencies.add(new String[]{"facture", "factures"});
        }
        uiModel.addAttribute("dependencies", dependencies);
        return "lignefactures/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String LigneFactureController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("lignefacture", LigneFacture.findLigneFacture(id));
        uiModel.addAttribute("itemId", id);
        return "lignefactures/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String LigneFactureController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("lignefactures", LigneFacture.findLigneFactureEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) LigneFacture.countLigneFactures() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("lignefactures", LigneFacture.findAllLigneFactures());
        }
        return "lignefactures/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String LigneFactureController.update(@Valid LigneFacture ligneFacture, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("ligneFacture", ligneFacture);
            return "lignefactures/update";
        }
        uiModel.asMap().clear();
        ligneFacture.merge();
        return "redirect:/lignefactures/" + encodeUrlPathSegment(ligneFacture.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String LigneFactureController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("ligneFacture", LigneFacture.findLigneFacture(id));
        return "lignefactures/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String LigneFactureController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        LigneFacture.findLigneFacture(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/lignefactures";
    }
    
    @ModelAttribute("factures")
    public Collection<Facture> LigneFactureController.populateFactures() {
        return Facture.findAllFactures();
    }
    
    @ModelAttribute("lignefactures")
    public Collection<LigneFacture> LigneFactureController.populateLigneFactures() {
        return LigneFacture.findAllLigneFactures();
    }
    
    String LigneFactureController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
