// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Inventaire;
import org.adorsys.adpharma.domain.LigneInventaire;
import org.adorsys.adpharma.domain.Produit;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect LigneInventaireController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String LigneInventaireController.create(@Valid LigneInventaire ligneInventaire, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("ligneInventaire", ligneInventaire);
            addDateTimeFormatPatterns(uiModel);
            return "ligneinventaires/create";
        }
        uiModel.asMap().clear();
        ligneInventaire.persist();
        return "redirect:/ligneinventaires/" + encodeUrlPathSegment(ligneInventaire.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String LigneInventaireController.createForm(Model uiModel) {
        uiModel.addAttribute("ligneInventaire", new LigneInventaire());
        addDateTimeFormatPatterns(uiModel);
        return "ligneinventaires/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String LigneInventaireController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("ligneinventaire", LigneInventaire.findLigneInventaire(id));
        uiModel.addAttribute("itemId", id);
        return "ligneinventaires/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String LigneInventaireController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("ligneinventaires", LigneInventaire.findLigneInventaireEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) LigneInventaire.countLigneInventaires() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("ligneinventaires", LigneInventaire.findAllLigneInventaires());
        }
        addDateTimeFormatPatterns(uiModel);
        return "ligneinventaires/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String LigneInventaireController.update(@Valid LigneInventaire ligneInventaire, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("ligneInventaire", ligneInventaire);
            addDateTimeFormatPatterns(uiModel);
            return "ligneinventaires/update";
        }
        uiModel.asMap().clear();
        ligneInventaire.merge();
        return "redirect:/ligneinventaires/" + encodeUrlPathSegment(ligneInventaire.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String LigneInventaireController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("ligneInventaire", LigneInventaire.findLigneInventaire(id));
        addDateTimeFormatPatterns(uiModel);
        return "ligneinventaires/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String LigneInventaireController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        LigneInventaire.findLigneInventaire(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/ligneinventaires";
    }
    
    @ModelAttribute("inventaires")
    public Collection<Inventaire> LigneInventaireController.populateInventaires() {
        return Inventaire.findAllInventaires();
    }
    
    @ModelAttribute("ligneinventaires")
    public Collection<LigneInventaire> LigneInventaireController.populateLigneInventaires() {
        return LigneInventaire.findAllLigneInventaires();
    }
    
    @ModelAttribute("produits")
    public Collection<Produit> LigneInventaireController.populateProduits() {
        return Produit.findAllProduits();
    }
    
    void LigneInventaireController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("ligneInventaire_datesaisie_date_format", "dd-MM-yyyy HH:mm");
    }
    
    String LigneInventaireController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
