// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.CommandeFournisseur;
import org.adorsys.adpharma.domain.LigneCmdFournisseur;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect LigneCmdFournisseurContoller_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByCommande", "form" }, method = RequestMethod.GET)
    public String LigneCmdFournisseurContoller.findLigneCmdFournisseursByCommandeForm(Model uiModel) {
        uiModel.addAttribute("commandefournisseurs", CommandeFournisseur.findAllCommandeFournisseurs());
        return "lignecmdfournisseurs/findLigneCmdFournisseursByCommande";
    }
    
    @RequestMapping(params = "find=ByCommande", method = RequestMethod.GET)
    public String LigneCmdFournisseurContoller.findLigneCmdFournisseursByCommande(@RequestParam("commande") CommandeFournisseur commande, Model uiModel) {
        uiModel.addAttribute("lignecmdfournisseurs", LigneCmdFournisseur.findLigneCmdFournisseursByCommande(commande).getResultList());
        return "lignecmdfournisseurs/list";
    }
    
}
