// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import java.math.BigInteger;
import org.adorsys.adpharma.domain.Approvisionement;
import org.adorsys.adpharma.domain.LigneApprovisionement;
import org.adorsys.adpharma.domain.Produit;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect LigneApprovisionementController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByApprovisionement", "form" }, method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByApprovisionementForm(Model uiModel) {
        uiModel.addAttribute("approvisionements", Approvisionement.findAllApprovisionements());
        return "ligneapprovisionements/findLigneApprovisionementsByApprovisionement";
    }
    
    @RequestMapping(params = "find=ByApprovisionement", method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByApprovisionement(@RequestParam("approvisionement") Approvisionement approvisionement, Model uiModel) {
        uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findLigneApprovisionementsByApprovisionement(approvisionement).getResultList());
        return "ligneapprovisionements/list";
    }
    
    @RequestMapping(params = { "find=ByCipMaisonEquals", "form" }, method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByCipMaisonEqualsForm(Model uiModel) {
        return "ligneapprovisionements/findLigneApprovisionementsByCipMaisonEquals";
    }
    
    @RequestMapping(params = "find=ByCipMaisonEquals", method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByCipMaisonEquals(@RequestParam("cipMaison") String cipMaison, Model uiModel) {
        uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findLigneApprovisionementsByCipMaisonEquals(cipMaison).getResultList());
        return "ligneapprovisionements/list";
    }
    
    @RequestMapping(params = { "find=ByDesignationLike", "form" }, method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByDesignationLikeForm(Model uiModel) {
        return "ligneapprovisionements/findLigneApprovisionementsByDesignationLike";
    }
    
    @RequestMapping(params = "find=ByDesignationLike", method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByDesignationLike(@RequestParam("designation") String designation, Model uiModel) {
        uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findLigneApprovisionementsByDesignationLike(designation).getResultList());
        return "ligneapprovisionements/list";
    }
    
    @RequestMapping(params = { "find=ByProduit", "form" }, method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByProduitForm(Model uiModel) {
        uiModel.addAttribute("produits", Produit.findAllProduits());
        return "ligneapprovisionements/findLigneApprovisionementsByProduit";
    }
    
    @RequestMapping(params = "find=ByProduit", method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByProduit(@RequestParam("produit") Produit produit, Model uiModel) {
        uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findLigneApprovisionementsByProduit(produit).getResultList());
        return "ligneapprovisionements/list";
    }
    
    @RequestMapping(params = { "find=ByQuantieEnStockAndCipEquals", "form" }, method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByQuantieEnStockAndCipEqualsForm(Model uiModel) {
        return "ligneapprovisionements/findLigneApprovisionementsByQuantieEnStockAndCipEquals";
    }
    
    @RequestMapping(params = "find=ByQuantieEnStockAndCipEquals", method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByQuantieEnStockAndCipEquals(@RequestParam("quantieEnStock") BigInteger quantieEnStock, @RequestParam("cip") String cip, Model uiModel) {
        uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findLigneApprovisionementsByQuantieEnStockAndCipEquals(quantieEnStock, cip).getResultList());
        return "ligneapprovisionements/list";
    }
    
    @RequestMapping(params = { "find=ByQuantieEnStockAndDesignationLike", "form" }, method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByQuantieEnStockAndDesignationLikeForm(Model uiModel) {
        return "ligneapprovisionements/findLigneApprovisionementsByQuantieEnStockAndDesignationLike";
    }
    
    @RequestMapping(params = "find=ByQuantieEnStockAndDesignationLike", method = RequestMethod.GET)
    public String LigneApprovisionementController.findLigneApprovisionementsByQuantieEnStockAndDesignationLike(@RequestParam("quantieEnStock") BigInteger quantieEnStock, @RequestParam("designation") String designation, Model uiModel) {
        uiModel.addAttribute("ligneapprovisionements", LigneApprovisionement.findLigneApprovisionementsByQuantieEnStockAndDesignationLike(quantieEnStock, designation).getResultList());
        return "ligneapprovisionements/list";
    }
    
}
