// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.ModeConditionement;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect ModeConditionementController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String ModeConditionementController.create(@Valid ModeConditionement modeConditionement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("modeConditionement", modeConditionement);
            return "modeconditionements/create";
        }
        uiModel.asMap().clear();
        modeConditionement.persist();
        return "redirect:/modeconditionements/" + encodeUrlPathSegment(modeConditionement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String ModeConditionementController.createForm(Model uiModel) {
        uiModel.addAttribute("modeConditionement", new ModeConditionement());
        return "modeconditionements/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String ModeConditionementController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("modeconditionement", ModeConditionement.findModeConditionement(id));
        uiModel.addAttribute("itemId", id);
        return "modeconditionements/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String ModeConditionementController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("modeconditionements", ModeConditionement.findModeConditionementEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) ModeConditionement.countModeConditionements() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("modeconditionements", ModeConditionement.findAllModeConditionements());
        }
        return "modeconditionements/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String ModeConditionementController.update(@Valid ModeConditionement modeConditionement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("modeConditionement", modeConditionement);
            return "modeconditionements/update";
        }
        uiModel.asMap().clear();
        modeConditionement.merge();
        return "redirect:/modeconditionements/" + encodeUrlPathSegment(modeConditionement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String ModeConditionementController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("modeConditionement", ModeConditionement.findModeConditionement(id));
        return "modeconditionements/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String ModeConditionementController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        ModeConditionement.findModeConditionement(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/modeconditionements";
    }
    
    @ModelAttribute("modeconditionements")
    public Collection<ModeConditionement> ModeConditionementController.populateModeConditionements() {
        return ModeConditionement.findAllModeConditionements();
    }
    
    String ModeConditionementController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
