// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import java.util.Date;
import org.adorsys.adpharma.domain.Caisse;
import org.adorsys.adpharma.domain.OperationCaisse;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect OperationCaisseController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByCaisse", "form" }, method = RequestMethod.GET)
    public String OperationCaisseController.findOperationCaissesByCaisseForm(Model uiModel) {
        uiModel.addAttribute("caisses", Caisse.findAllCaisses());
        return "operationcaisses/findOperationCaissesByCaisse";
    }
    
    @RequestMapping(params = "find=ByCaisse", method = RequestMethod.GET)
    public String OperationCaisseController.findOperationCaissesByCaisse(@RequestParam("caisse") Caisse caisse, Model uiModel) {
        uiModel.addAttribute("operationcaisses", OperationCaisse.findOperationCaissesByCaisse(caisse).getResultList());
        return "operationcaisses/list";
    }
    
    @RequestMapping(params = { "find=ByDateOperationBetween", "form" }, method = RequestMethod.GET)
    public String OperationCaisseController.findOperationCaissesByDateOperationBetweenForm(Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        return "operationcaisses/findOperationCaissesByDateOperationBetween";
    }
    
    @RequestMapping(params = "find=ByDateOperationBetween", method = RequestMethod.GET)
    public String OperationCaisseController.findOperationCaissesByDateOperationBetween(@RequestParam("minDateOperation") @DateTimeFormat(pattern = "dd-MM-yyyy HH:mm") Date minDateOperation, @RequestParam("maxDateOperation") @DateTimeFormat(pattern = "dd-MM-yyyy HH:mm") Date maxDateOperation, Model uiModel) {
        uiModel.addAttribute("operationcaisses", OperationCaisse.findOperationCaissesByDateOperationBetween(minDateOperation, maxDateOperation).getResultList());
        addDateTimeFormatPatterns(uiModel);
        return "operationcaisses/list";
    }
    
}
