// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.CommandeClient;
import org.adorsys.adpharma.domain.Ordonnancier;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect OrdonnancierController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByCommande", "form" }, method = RequestMethod.GET)
    public String OrdonnancierController.findOrdonnanciersByCommandeForm(Model uiModel) {
        uiModel.addAttribute("commandeclients", CommandeClient.findAllCommandeClients());
        return "ordonnanciers/findOrdonnanciersByCommande";
    }
    
    @RequestMapping(params = "find=ByCommande", method = RequestMethod.GET)
    public String OrdonnancierController.findOrdonnanciersByCommande(@RequestParam("commande") CommandeClient commande, Model uiModel) {
        uiModel.addAttribute("ordonnanciers", Ordonnancier.findOrdonnanciersByCommande(commande).getResultList());
        return "ordonnanciers/list";
    }
    
    @RequestMapping(params = { "find=ByOrdNumberEquals", "form" }, method = RequestMethod.GET)
    public String OrdonnancierController.findOrdonnanciersByOrdNumberEqualsForm(Model uiModel) {
        return "ordonnanciers/findOrdonnanciersByOrdNumberEquals";
    }
    
    @RequestMapping(params = "find=ByOrdNumberEquals", method = RequestMethod.GET)
    public String OrdonnancierController.findOrdonnanciersByOrdNumberEquals(@RequestParam("ordNumber") String ordNumber, Model uiModel) {
        uiModel.addAttribute("ordonnanciers", Ordonnancier.findOrdonnanciersByOrdNumberEquals(ordNumber).getResultList());
        return "ordonnanciers/list";
    }
    
}
