// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Arrays;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.Caisse;
import org.adorsys.adpharma.domain.Facture;
import org.adorsys.adpharma.domain.Paiement;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.QuiPaye;
import org.adorsys.adpharma.domain.Site;
import org.adorsys.adpharma.domain.TypePaiement;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect PaiementController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String PaiementController.create(@Valid Paiement paiement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("paiement", paiement);
            addDateTimeFormatPatterns(uiModel);
            return "paiements/create";
        }
        uiModel.asMap().clear();
        paiement.persist();
        return "redirect:/paiements/" + encodeUrlPathSegment(paiement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String PaiementController.createForm(Model uiModel) {
        uiModel.addAttribute("paiement", new Paiement());
        addDateTimeFormatPatterns(uiModel);
        return "paiements/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String PaiementController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("paiement", Paiement.findPaiement(id));
        uiModel.addAttribute("itemId", id);
        return "paiements/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String PaiementController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("paiements", Paiement.findPaiementEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) Paiement.countPaiements() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("paiements", Paiement.findAllPaiements());
        }
        addDateTimeFormatPatterns(uiModel);
        return "paiements/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String PaiementController.update(@Valid Paiement paiement, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("paiement", paiement);
            addDateTimeFormatPatterns(uiModel);
            return "paiements/update";
        }
        uiModel.asMap().clear();
        paiement.merge();
        return "redirect:/paiements/" + encodeUrlPathSegment(paiement.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String PaiementController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("paiement", Paiement.findPaiement(id));
        addDateTimeFormatPatterns(uiModel);
        return "paiements/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String PaiementController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Paiement.findPaiement(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/paiements";
    }
    
    void PaiementController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("paiement_datepaiement_date_format", "dd-MM-yyyy HH:mm");
        uiModel.addAttribute("paiement_datesaisie_date_format", "dd-MM-yyyy HH:mm");
    }
    
    String PaiementController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
