// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.PharmaUser;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect PharmaUserController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=BySaleKeyEquals", "form" }, method = RequestMethod.GET)
    public String PharmaUserController.findPharmaUsersBySaleKeyEqualsForm(Model uiModel) {
        return "pharmausers/findPharmaUsersBySaleKeyEquals";
    }
    
    @RequestMapping(params = "find=BySaleKeyEquals", method = RequestMethod.GET)
    public String PharmaUserController.findPharmaUsersBySaleKeyEquals(@RequestParam("saleKey") String saleKey, Model uiModel) {
        uiModel.addAttribute("pharmausers", PharmaUser.findPharmaUsersBySaleKeyEquals(saleKey).getResultList());
        return "pharmausers/list";
    }
    
    @RequestMapping(params = { "find=ByUserNameEquals", "form" }, method = RequestMethod.GET)
    public String PharmaUserController.findPharmaUsersByUserNameEqualsForm(Model uiModel) {
        return "pharmausers/findPharmaUsersByUserNameEquals";
    }
    
    @RequestMapping(params = "find=ByUserNameEquals", method = RequestMethod.GET)
    public String PharmaUserController.findPharmaUsersByUserNameEquals(@RequestParam("userName") String userName, Model uiModel) {
        uiModel.addAttribute("pharmausers", PharmaUser.findPharmaUsersByUserNameEquals(userName).getResultList());
        return "pharmausers/list";
    }
    
    @RequestMapping(params = { "find=ByUserNameLike", "form" }, method = RequestMethod.GET)
    public String PharmaUserController.findPharmaUsersByUserNameLikeForm(Model uiModel) {
        return "pharmausers/findPharmaUsersByUserNameLike";
    }
    
    @RequestMapping(params = "find=ByUserNameLike", method = RequestMethod.GET)
    public String PharmaUserController.findPharmaUsersByUserNameLike(@RequestParam("userName") String userName, Model uiModel) {
        uiModel.addAttribute("pharmausers", PharmaUser.findPharmaUsersByUserNameLike(userName).getResultList());
        return "pharmausers/list";
    }
    
}
