// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import org.adorsys.adpharma.domain.PrinterConfiguration;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect PrinterConfigurationController_Roo_Controller {
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String PrinterConfigurationController.createForm(Model uiModel) {
        uiModel.addAttribute("printerConfiguration", new PrinterConfiguration());
        return "printerconfigurations/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String PrinterConfigurationController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("printerconfiguration", PrinterConfiguration.findPrinterConfiguration(id));
        uiModel.addAttribute("itemId", id);
        return "printerconfigurations/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String PrinterConfigurationController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("printerconfigurations", PrinterConfiguration.findPrinterConfigurationEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) PrinterConfiguration.countPrinterConfigurations() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("printerconfigurations", PrinterConfiguration.findAllPrinterConfigurations());
        }
        return "printerconfigurations/list";
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String PrinterConfigurationController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("printerConfiguration", PrinterConfiguration.findPrinterConfiguration(id));
        return "printerconfigurations/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String PrinterConfigurationController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        PrinterConfiguration.findPrinterConfiguration(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/printerconfigurations";
    }
    
    @ModelAttribute("printerconfigurations")
    public Collection<PrinterConfiguration> PrinterConfigurationController.populatePrinterConfigurations() {
        return PrinterConfiguration.findAllPrinterConfigurations();
    }
    
    String PrinterConfigurationController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
