// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.Rayon;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect RayonController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByDisplayNameEquals", "form" }, method = RequestMethod.GET)
    public String RayonController.findRayonsByDisplayNameEqualsForm(Model uiModel) {
        return "rayons/findRayonsByDisplayNameEquals";
    }
    
    @RequestMapping(params = "find=ByDisplayNameEquals", method = RequestMethod.GET)
    public String RayonController.findRayonsByDisplayNameEquals(@RequestParam("displayName") String displayName, Model uiModel) {
        uiModel.addAttribute("rayons", Rayon.findRayonsByDisplayNameEquals(displayName).getResultList());
        return "rayons/list";
    }
    
    @RequestMapping(params = { "find=ByDisplayNameLike", "form" }, method = RequestMethod.GET)
    public String RayonController.findRayonsByDisplayNameLikeForm(Model uiModel) {
        return "rayons/findRayonsByDisplayNameLike";
    }
    
    @RequestMapping(params = "find=ByDisplayNameLike", method = RequestMethod.GET)
    public String RayonController.findRayonsByDisplayNameLike(@RequestParam("displayName") String displayName, Model uiModel) {
        uiModel.addAttribute("rayons", Rayon.findRayonsByDisplayNameLike(displayName).getResultList());
        return "rayons/list";
    }
    
    @RequestMapping(params = { "find=ByNameEquals", "form" }, method = RequestMethod.GET)
    public String RayonController.findRayonsByNameEqualsForm(Model uiModel) {
        return "rayons/findRayonsByNameEquals";
    }
    
    @RequestMapping(params = "find=ByNameEquals", method = RequestMethod.GET)
    public String RayonController.findRayonsByNameEquals(@RequestParam("name") String name, Model uiModel) {
        uiModel.addAttribute("rayons", Rayon.findRayonsByNameEquals(name).getResultList());
        return "rayons/list";
    }
    
    @RequestMapping(params = { "find=ByNameLike", "form" }, method = RequestMethod.GET)
    public String RayonController.findRayonsByNameLikeForm(Model uiModel) {
        return "rayons/findRayonsByNameLike";
    }
    
    @RequestMapping(params = "find=ByNameLike", method = RequestMethod.GET)
    public String RayonController.findRayonsByNameLike(@RequestParam("name") String name, Model uiModel) {
        uiModel.addAttribute("rayons", Rayon.findRayonsByNameLike(name).getResultList());
        return "rayons/list";
    }
    
}
