// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.SalesConfiguration;
import org.adorsys.adpharma.domain.TypeVente;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect SalesConfigurationController_Roo_Controller_Finder {
    
    @RequestMapping(params = { "find=ByTypeVente", "form" }, method = RequestMethod.GET)
    public String SalesConfigurationController.findSalesConfigurationsByTypeVenteForm(Model uiModel) {
        uiModel.addAttribute("typeventes", java.util.Arrays.asList(TypeVente.class.getEnumConstants()));
        return "salesconfigurations/findSalesConfigurationsByTypeVente";
    }
    
    @RequestMapping(params = "find=ByTypeVente", method = RequestMethod.GET)
    public String SalesConfigurationController.findSalesConfigurationsByTypeVente(@RequestParam("typeVente") TypeVente typeVente, Model uiModel) {
        uiModel.addAttribute("salesconfigurations", SalesConfiguration.findSalesConfigurationsByTypeVente(typeVente).getResultList());
        return "salesconfigurations/list";
    }
    
}
