// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.SortieProduit;
import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect SortieProduitController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String SortieProduitController.create(@Valid SortieProduit sortieProduit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("sortieProduit", sortieProduit);
            addDateTimeFormatPatterns(uiModel);
            return "sortieproduits/create";
        }
        uiModel.asMap().clear();
        sortieProduit.persist();
        return "redirect:/sortieproduits/" + encodeUrlPathSegment(sortieProduit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String SortieProduitController.createForm(Model uiModel) {
        uiModel.addAttribute("sortieProduit", new SortieProduit());
        addDateTimeFormatPatterns(uiModel);
        return "sortieproduits/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String SortieProduitController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("sortieproduit", SortieProduit.findSortieProduit(id));
        uiModel.addAttribute("itemId", id);
        return "sortieproduits/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String SortieProduitController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("sortieproduits", SortieProduit.findSortieProduitEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) SortieProduit.countSortieProduits() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("sortieproduits", SortieProduit.findAllSortieProduits());
        }
        addDateTimeFormatPatterns(uiModel);
        return "sortieproduits/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String SortieProduitController.update(@Valid SortieProduit sortieProduit, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("sortieProduit", sortieProduit);
            addDateTimeFormatPatterns(uiModel);
            return "sortieproduits/update";
        }
        uiModel.asMap().clear();
        sortieProduit.merge();
        return "redirect:/sortieproduits/" + encodeUrlPathSegment(sortieProduit.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String SortieProduitController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("sortieProduit", SortieProduit.findSortieProduit(id));
        addDateTimeFormatPatterns(uiModel);
        return "sortieproduits/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String SortieProduitController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        SortieProduit.findSortieProduit(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/sortieproduits";
    }
    
    @ModelAttribute("sortieproduits")
    public Collection<SortieProduit> SortieProduitController.populateSortieProduits() {
        return SortieProduit.findAllSortieProduits();
    }
    
    void SortieProduitController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("sortieProduit_datesaisie_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    String SortieProduitController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
