// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.Long;
import java.lang.String;
import org.adorsys.adpharma.domain.Produit;
import org.adorsys.adpharma.domain.TransformationProduit;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

privileged aspect TransformationProduitController_Roo_Controller_Json {
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET, headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> TransformationProduitController.showJson(@PathVariable("id") Long id) {
        TransformationProduit transformationproduit = TransformationProduit.findTransformationProduit(id);
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/text; charset=utf-8");
        if (transformationproduit == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(transformationproduit.toJson(), headers, HttpStatus.OK);
    }
    
    @RequestMapping(headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> TransformationProduitController.listJson() {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/text; charset=utf-8");
        return new ResponseEntity<String>(TransformationProduit.toJsonArray(TransformationProduit.findAllTransformationProduits()), headers, HttpStatus.OK);
    }
    
    @RequestMapping(method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> TransformationProduitController.createFromJson(@RequestBody String json) {
        TransformationProduit.fromJsonToTransformationProduit(json).persist();
        HttpHeaders headers= new HttpHeaders();
        headers.add("Content-Type", "application/text");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(value = "/jsonArray", method = RequestMethod.POST, headers = "Accept=application/json")
    public ResponseEntity<String> TransformationProduitController.createFromJsonArray(@RequestBody String json) {
        for (TransformationProduit transformationProduit: TransformationProduit.fromJsonArrayToTransformationProduits(json)) {
            transformationProduit.persist();
        }
        HttpHeaders headers= new HttpHeaders();
        headers.add("Content-Type", "application/text");
        return new ResponseEntity<String>(headers, HttpStatus.CREATED);
    }
    
    @RequestMapping(method = RequestMethod.PUT, headers = "Accept=application/json")
    public ResponseEntity<String> TransformationProduitController.updateFromJson(@RequestBody String json) {
        HttpHeaders headers= new HttpHeaders();
        headers.add("Content-Type", "application/text");
        if (TransformationProduit.fromJsonToTransformationProduit(json).merge() == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/jsonArray", method = RequestMethod.PUT, headers = "Accept=application/json")
    public ResponseEntity<String> TransformationProduitController.updateFromJsonArray(@RequestBody String json) {
        HttpHeaders headers= new HttpHeaders();
        headers.add("Content-Type", "application/text");
        for (TransformationProduit transformationProduit: TransformationProduit.fromJsonArrayToTransformationProduits(json)) {
            if (transformationProduit.merge() == null) {
                return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
            }
        }
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, headers = "Accept=application/json")
    public ResponseEntity<String> TransformationProduitController.deleteFromJson(@PathVariable("id") Long id) {
        TransformationProduit transformationproduit = TransformationProduit.findTransformationProduit(id);
        HttpHeaders headers= new HttpHeaders();
        headers.add("Content-Type", "application/text");
        if (transformationproduit == null) {
            return new ResponseEntity<String>(headers, HttpStatus.NOT_FOUND);
        }
        transformationproduit.remove();
        return new ResponseEntity<String>(headers, HttpStatus.OK);
    }
    
    @RequestMapping(params = "find=ByProduitOrigine", method = RequestMethod.GET, headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> TransformationProduitController.jsonFindTransformationProduitsByProduitOrigine(@RequestParam("produitOrigine") Produit produitOrigine) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/text; charset=utf-8");
        return new ResponseEntity<String>(TransformationProduit.toJsonArray(TransformationProduit.findTransformationProduitsByProduitOrigine(produitOrigine).getResultList()), headers, HttpStatus.OK);
    }
    
    @RequestMapping(params = "find=ByProduitOrigineAndProduitCible", method = RequestMethod.GET, headers = "Accept=application/json")
    @ResponseBody
    public ResponseEntity<String> TransformationProduitController.jsonFindTransformationProduitsByProduitOrigineAndProduitCible(@RequestParam("produitOrigine") Produit produitOrigine, @RequestParam("produitCible") Produit produitCible) {
        HttpHeaders headers = new HttpHeaders();
        headers.add("Content-Type", "application/text; charset=utf-8");
        return new ResponseEntity<String>(TransformationProduit.toJsonArray(TransformationProduit.findTransformationProduitsByProduitOrigineAndProduitCible(produitOrigine, produitCible).getResultList()), headers, HttpStatus.OK);
    }
    
}
