// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.lang.String;
import org.adorsys.adpharma.domain.Produit;
import org.adorsys.adpharma.domain.TransformationProduit;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

privileged aspect TransformationProduitController_Roo_Controller_Finder {
    
    @RequestMapping(params = "find=ByProduitOrigine", method = RequestMethod.GET)
    public String TransformationProduitController.findTransformationProduitsByProduitOrigine(@RequestParam("produitOrigine") Produit produitOrigine, Model uiModel) {
        uiModel.addAttribute("transformationproduits", TransformationProduit.findTransformationProduitsByProduitOrigine(produitOrigine).getResultList());
        return "transformationproduits/list";
    }
    
    @RequestMapping(params = { "find=ByProduitOrigineAndProduitCible", "form" }, method = RequestMethod.GET)
    public String TransformationProduitController.findTransformationProduitsByProduitOrigineAndProduitCibleForm(Model uiModel) {
        uiModel.addAttribute("produits", Produit.findAllProduits());
        uiModel.addAttribute("produits", Produit.findAllProduits());
        return "transformationproduits/findTransformationProduitsByProduitOrigineAndProduitCible";
    }
    
    @RequestMapping(params = "find=ByProduitOrigineAndProduitCible", method = RequestMethod.GET)
    public String TransformationProduitController.findTransformationProduitsByProduitOrigineAndProduitCible(@RequestParam("produitOrigine") Produit produitOrigine, @RequestParam("produitCible") Produit produitCible, Model uiModel) {
        uiModel.addAttribute("transformationproduits", TransformationProduit.findTransformationProduitsByProduitOrigineAndProduitCible(produitOrigine, produitCible).getResultList());
        return "transformationproduits/list";
    }
    
}
