// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.web;

import java.io.UnsupportedEncodingException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Collection;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.adorsys.adpharma.domain.TVA;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;

privileged aspect TVAControlleur_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST)
    public String TVAControlleur.create(@Valid TVA TVA, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("TVA", TVA);
            return "tvas/create";
        }
        uiModel.asMap().clear();
        TVA.persist();
        return "redirect:/tvas/" + encodeUrlPathSegment(TVA.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", method = RequestMethod.GET)
    public String TVAControlleur.createForm(Model uiModel) {
        uiModel.addAttribute("TVA", new TVA());
        return "tvas/create";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.GET)
    public String TVAControlleur.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("tva", TVA.findTVA(id));
        uiModel.addAttribute("itemId", id);
        return "tvas/show";
    }
    
    @RequestMapping(method = RequestMethod.GET)
    public String TVAControlleur.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            uiModel.addAttribute("tvas", TVA.findTVAEntries(page == null ? 0 : (page.intValue() - 1) * sizeNo, sizeNo));
            float nrOfPages = (float) TVA.countTVAS() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("tvas", TVA.findAllTVAS());
        }
        return "tvas/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT)
    public String TVAControlleur.update(@Valid TVA TVA, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            uiModel.addAttribute("TVA", TVA);
            return "tvas/update";
        }
        uiModel.asMap().clear();
        TVA.merge();
        return "redirect:/tvas/" + encodeUrlPathSegment(TVA.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", method = RequestMethod.GET)
    public String TVAControlleur.updateForm(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("TVA", TVA.findTVA(id));
        return "tvas/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
    public String TVAControlleur.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        TVA.findTVA(id).remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/tvas";
    }
    
    @ModelAttribute("tvas")
    public Collection<TVA> TVAControlleur.populateTVAS() {
        return TVA.findAllTVAS();
    }
    
    String TVAControlleur.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        }
        catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
