// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain.virtualtable;

import java.lang.String;

privileged aspect ClientV_Roo_JavaBean {
    
    public String ClientV.getName() {
        return this.name;
    }
    
    public void ClientV.setName(String name) {
        this.name = name;
    }
    
    public String ClientV.getTypeClient() {
        return this.typeClient;
    }
    
    public void ClientV.setTypeClient(String typeClient) {
        this.typeClient = typeClient;
    }
    
    public String ClientV.getEmployeur() {
        return this.employeur;
    }
    
    public void ClientV.setEmployeur(String employeur) {
        this.employeur = employeur;
    }
    
    public String ClientV.getPayeur() {
        return this.payeur;
    }
    
    public void ClientV.setPayeur(String payeur) {
        this.payeur = payeur;
    }
    
}
