// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain.virtualtable;

import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Version;
import org.adorsys.adpharma.domain.virtualtable.ClientV;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ClientV_Roo_Entity {
    
    declare @type: ClientV: @Entity;
    
    @PersistenceContext
    transient EntityManager ClientV.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long ClientV.id;
    
    @Version
    @Column(name = "version")
    private Integer ClientV.version;
    
    public Long ClientV.getId() {
        return this.id;
    }
    
    public void ClientV.setId(Long id) {
        this.id = id;
    }
    
    public Integer ClientV.getVersion() {
        return this.version;
    }
    
    public void ClientV.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void ClientV.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void ClientV.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            ClientV attached = ClientV.findClientV(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void ClientV.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void ClientV.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public ClientV ClientV.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        ClientV merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager ClientV.entityManager() {
        EntityManager em = new ClientV().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long ClientV.countClientVs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM ClientV o", Long.class).getSingleResult();
    }
    
    public static List<ClientV> ClientV.findAllClientVs() {
        return entityManager().createQuery("SELECT o FROM ClientV o", ClientV.class).getResultList();
    }
    
    public static ClientV ClientV.findClientV(Long id) {
        if (id == null) return null;
        return entityManager().find(ClientV.class, id);
    }
    
    public static List<ClientV> ClientV.findClientVEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM ClientV o", ClientV.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
