// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain.virtualtable;

import org.adorsys.adpharma.domain.virtualtable.ProduitV;

privileged aspect ProduitV_Roo_JavaBean {
    
    public String ProduitV.getCip() {
        return this.cip;
    }
    
    public void ProduitV.setCip(String cip) {
        this.cip = cip;
    }
    
    public String ProduitV.getCipMaison() {
        return this.cipMaison;
    }
    
    public void ProduitV.setCipMaison(String cipMaison) {
        this.cipMaison = cipMaison;
    }
    
    public String ProduitV.getDesignation() {
        return this.designation;
    }
    
    public void ProduitV.setDesignation(String designation) {
        this.designation = designation;
    }
    
    public String ProduitV.getQte() {
        return this.qte;
    }
    
    public void ProduitV.setQte(String qte) {
        this.qte = qte;
    }
    
    public String ProduitV.getPachat() {
        return this.pachat;
    }
    
    public void ProduitV.setPachat(String pachat) {
        this.pachat = pachat;
    }
    
    public String ProduitV.getPvente() {
        return this.pvente;
    }
    
    public void ProduitV.setPvente(String pvente) {
        this.pvente = pvente;
    }
    
    public String ProduitV.getFiliale() {
        return this.filiale;
    }
    
    public void ProduitV.setFiliale(String filiale) {
        this.filiale = filiale;
    }
    
    public String ProduitV.getRayon() {
        return this.rayon;
    }
    
    public void ProduitV.setRayon(String rayon) {
        this.rayon = rayon;
    }
    
}
