// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.domain.virtualtable;

import java.lang.String;

privileged aspect ProduitV_Roo_ToString {
    
    public String ProduitV.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Cip: ").append(getCip()).append(", ");
        sb.append("CipMaison: ").append(getCipMaison()).append(", ");
        sb.append("Designation: ").append(getDesignation()).append(", ");
        sb.append("Filiale: ").append(getFiliale()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Pachat: ").append(getPachat()).append(", ");
        sb.append("Pvente: ").append(getPvente()).append(", ");
        sb.append("Qte: ").append(getQte()).append(", ");
        sb.append("Rayon: ").append(getRayon()).append(", ");
        sb.append("Version: ").append(getVersion());
        return sb.toString();
    }
    
}
