// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.adorsys.adpharma.beans.process;

import java.lang.Long;
import java.lang.String;
import java.util.List;
import org.adorsys.adpharma.domain.LigneInventaire;
import org.adorsys.adpharma.domain.PharmaUser;
import org.adorsys.adpharma.domain.Produit;

privileged aspect InventaireProcess_Roo_JavaBean {
    
    public Long InventaireProcess.getInvId() {
        return this.invId;
    }
    
    public void InventaireProcess.setInvId(Long invId) {
        this.invId = invId;
    }
    
    public Produit InventaireProcess.getProduit() {
        return this.produit;
    }
    
    public void InventaireProcess.setProduit(Produit produit) {
        this.produit = produit;
    }
    
    public LigneInventaire InventaireProcess.getLineToUpdate() {
        return this.lineToUpdate;
    }
    
    public void InventaireProcess.setLineToUpdate(LigneInventaire lineToUpdate) {
        this.lineToUpdate = lineToUpdate;
    }
    
    public List<LigneInventaire> InventaireProcess.getProductSelected() {
        return this.productSelected;
    }
    
    public void InventaireProcess.setProductSelected(List<LigneInventaire> productSelected) {
        this.productSelected = productSelected;
    }
    
    public List<Produit> InventaireProcess.getProductResult() {
        return this.productResult;
    }
    
    public void InventaireProcess.setProductResult(List<Produit> productResult) {
        this.productResult = productResult;
    }
    
    public String InventaireProcess.getDisplayName() {
        return this.displayName;
    }
    
    public void InventaireProcess.setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    
    public PharmaUser InventaireProcess.getAgent() {
        return this.agent;
    }
    
    public void InventaireProcess.setAgent(PharmaUser agent) {
        this.agent = agent;
    }
    
}
